### ISSUE TITLE
type definition in signature file wrapped with hash directives

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1115]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwANAHQCcL1raAXATwNIFV0r9YAbAN0TwAgnjyJsAIx5MASogBmiLuhJgAvGA5c8vAcNHipshUsQrSseWDwMqAS3QBzMACowIsZOlzFy1TzsbejoadABiOysAQgA5AHkAfQBRMgAVJJiAZQBJOJjUgE0ABWyYgHFg5lYwOR1%2BQSSADwYzPDtYdB9Tc3Ua7nr4Jpb0No6uvwsrG3snV3cDL2NfM39AhjnUzAcW%2BAAebNSWRCKqWD47JCoAPjAAoNCws3hIyAAacCgxBgYHRzxUMAAbQ%2BEFAEHBUAAJFVkGhINs3iDwZBIXxMDwAK6woFIiEABneEIhkGy6CQ6AYmTsAC9kISiRAACy4sAAXSRAF96aCWSiYQD4RTEQyUWjMdjgQyIABGblEyAAWUwjQAMg5ECqzI4GAALYVS6UAJjxLPZEK5SLB8uhRwFElgvH1xNR6KxAMlUsNcuJmXEdjgPA6QgYSTJcXkavQdJZEHk6LEps5cqtzv5cPtju9ULFbrQHoZAGYsxBIJkiCQAEIKWBcIqYKg4RAtKhOom2LGJ83J3k21h2h08Vsll3i90xsCM4tQMvERBV%2BQ1jWwADuSmgmDEpL4sHXPw6Q-B7cQnfBFohKeRvexkAzg6zotdEvHAFYp6Xy3Pq1w2ARWFR15u6Dbru7ToAesbxseDJmqe3Yile-aZj2OZPlKYAAGxvjOlZfogADCPAbngeEdNMGLQAwNbgWAcY8Am0FJpaPZplAt4Hg%2Bo55uOADsWEfvOi4KoYSjUbR9FEjBEBnuCF7DixN4DuxI65jiaEABx8bOAlcCRgZgVOYlQRJjHnsxtrpop97KahUoAJyaSQQjyM2JHYNgmDUUeJ5SXB1ryWxVkoWOaHSgS47vlpuG%2Btg-q8PuBmQd5YDSTy8H%2BZZyGPsFBqyuF2GIE5zbRbFemeVQHYMV2TFpeZrEZfBQVcSFXrhaS5IMHE6CpFQTAAOp2LqomJZVsHVX5tUKUhDVZU1BpFnlH5CKcGJkgAIogAQxc2ZUVcZVWmTVfZwgigUzapBqTuFSqNNk8ipDqZhJHRiCZDqNYMP18CDVOjImiNPljamE0nZlnHnQy0qvldyqkvIdiNHEf6YJRVBNAQ2ijPpL5-Xto0HeNR1QCD01g-mRLSph0ONHIcBUPAn3feOv1JSlYCyVC8nE9ajXg%2BTvFU0tDZMHEVBqjYDN6j9OMQpJyW%2BUDhOCgwSk82TELShpVMAGqPhWDjPE4EvUcz-1y4Dl6c0Kp2k%2BO0r2VTABiK0UaBetkr8RtSyz8sWxNAWgypavgsab4KhiPA-AEUYVoG0AANYVg28dNngnWZI2ukYtgWNoYZ3vm3Jfv1dzZ1BxAhq5WhkAxIgy5R5%2BDCrmYhysOtcPoANoFCGSQmSEo-wJc9%2Bf4wr17%2ByTgfjoaLVVwA0ogiAELd91mKS6e4JG0a58NuMAyPvuK1zzqq1P81V9dT0xXgOqe0z0vgrLrPs3yRdTSXNtoYal1V1STg8AVVBHBZzMB9RAEgFQIC3lKPOpsn5mUVuPd%2Bk9P5QyrkIAIjh0BOxUHudAVJMHIwxFwVIsA2ogORqBIaQ9YE%2B0Lgg4ux9S5T0pmgiOSgsA-AECqDojhe4SCUG3BwndSJUPEjLEyMl4FjwYZeE%2Bn9%2BY-1sP6BgECkCiKMuI80HxWT0nhHgB2bQAReQ5EAA)

#### Code

```fsharp
namespace X

type UnresolvedAssemblyReference = UnresolvedAssemblyReference of string * AssemblyReference list

#if !NO_EXTENSIONTYPING
type ResolvedExtensionReference = ResolvedExtensionReference of string * AssemblyReference list * Tainted<ITypeProvider> list
#endif
```
            

#### Error

```fsharp
System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back togheter. Please raise an issue at https://github.com/fsprojects/fantomas/issues.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
   at Fantomas.String.merge(String a, String b) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Utils.fs:line 63
   at Fantomas.CodeFormatterImpl.merged@421.Invoke(String a, String b) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 421
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 234
   at Fantomas.CodeFormatterImpl.format@412-1.Invoke(Tuple`2[] _arg1) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 421
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 416
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
```
            
#### Problem description

Most likely a trivia problem regarding one of the hash directives.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 09/05/2020 10:04:29 - 9fed8b884aa63f47581f546203967c3160166cac

Default Fantomas configuration

**Comment by nojaf** [comment]
Regression compared to v4.0

**Comment by nojaf** [comment]
The trivia bug here is not a regression, only occurs in signature files.
