### ISSUE TITLE
Extra space throws exception

### ISSUE THREAD

**Issue by theothornhill** [fsprojects/fantomas#1476]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzMAPMBeMAtgIYAu0AFtmAO4CWJ5AOgE6MB2EnYAPmAKxgAtAD4W7LhLDAwRaCQCuRADZ4xHSRog5EWAA6I5ieAHk2iY5nwBtMAE5bazU%2BdOAbI5efPADg9f-GgCMAAx%2BAeEQgQBMYREBgQAssXFege6s6inxvhlZ4VGhuXn%2BUXzJxZoAzIXiFZ4JNZl1TnzBYAC6YAC%2BkAA04FAAzogkJLRsAOaDqGBWAxCgkpAAJCQAnvozkOMkffOcKwBuyvLIaHOawf2akACSbEhsJADKtABeyNcaCfsQ7ftdL4LX5QVYbM5QHZ7JbLY5KU4zC5BIESSAAWSIWAAMuNEFjEJMGNCggUQf8uID9otUWDNmhIAAjWCwJTErhHE4QpGSKIo9nPRAEWhwJSwNgAQRIAFEHhYcWY2RJ0MphmSASjqezaRDGczWXzQXCEecQRBKgaIJBnrpZIgAEKIdCwZiIAAKRGYRAII0QzEVXBIzFOaopGpBK3WdKgTJZ-sNnMRprACQtUGttodTpdWNg1F90CIw3uh1gBbGYrjEEDwck5M4lK4moO2q2Mf14dhCZNmj4qatNug9sdzsQAFVdPpmAWi2wS2XaBXU8qlKra%2BqqR3Izq23GOfCuUnXH304PMyOAMJKQuDc9iwbVuTOytgZeriR1iANzhNy0t%2Bk7g092NWYkwAdmPAchyzRA0UFBlfWfV9EBDeswxhLdWz1XdO33RNNG8CCM2HF1b1FNhEJVZC11DDd0PBTDY0AnDgO5CRbEIwdxXQEhfVvAhiGfasqPfddG03ej-ywpijQPTQQg4qCRwFIURUXJMkJQz80JpDDJMYjsZLwoJAgUrieOYZThRZNTNCEzTum0rVdOjKSDK7EC5N5JM7geAkSFMAAVZg1gAdXocgKJXYSuA-BzaJ0iSXP0mFDO7IJzW8k9EHFZhYHkB4ABFECUWghXMwSg2izhYq-YE6KjbYnmw1KPKCFNvIxLBbnQALyAJKUouechnRIML4CJVMGns2qpHEhqoWk9zWK4QJew6zF7nQWgsGMSdSGdKU9BdQZBgXcjU1aabHObZzGt2RbcLSyQ0j7TqACUDGdeAxompMpuo1D4qcxK7uapak0CcD1qwD64GYeAADl5AIeDmAsW4eIIaZU0CK6gZukGCHkJQxhKswADFnWIUZfQC%2BiHpYiGCO82GvrRYnSdxSnmGp8q%2BwoD1ZHMgB9OhxoivGxPqnUFrcx7Wue9joZyz01mMZgcXvH6Ism4JJe-OaZaahnZI0ApXsxFWiDVjXaHvJGUd9dHMexiH9bqhKGqJknaDJxBud52n6blxnNCiEzvKtm3NZIdmfb9gPSD57yBc9QxmFF2hxcgd3ZulrZZZS8Gw68m5OoANU5O1xngcYJm159-pEmipc9o37pD02eQysvMXJ-K5DO6uHjrhvddzn9QVuwuaRa5bOCidre6wArYBIABxEZDt0Y7TrFMek0ugGtPx39boAzujJ5Nay4533cTtUVoAAaztNPn5GQZTGeL1EFI5HzrqUohPQ2DF2xF3lvPCAUQjzeQRogagfsHQkDzASOm%2BgipbTYPQM64oHiwUdswV2mgNLHziq3YGDUL4QNDmbKGNwADSiBEC6G6r1Ak9wf7enlJ8IBUUQH53pDPLUc8kxRGZsvAaQpBjkAPpoJuMVRIG0EUlcBs9i5myVjcV4kwlDZWYBMZGfkQqIAZGiBAvCSHALITNSeEYQbUPUZApM1Q%2BzihKhMNg-c2CDzFK8TxpB5AugCrAe4jwSCkDOpFN8iiW7KLbmAsGziqgRxuO48ybBImHDxGKCYBDUaYPGDgu80Sqp-CUR7Sh25XI0K7hISopcNDojvjwrEXoGTwCIJeWAp1JjwMQbiUpAiEl6TUSIjRkhKg9yaQVO2RAGR6KkXbcgzw1hPExEMmx10z4gwJCYdAPDnjrD0Uk2hkyl5NJlPsnhz4YDMCUOgHOWzT5TwcTUpxZz6k3yaUc5gwpY4WM2c3esAx2hfG2IMcmp0ZgaS6EAA)

Hi there, and thanks for `4.4.0`

#### Code

```fsharp
f x = match x with
      | 5 ->
          { actual =
                x expectedOneOf = [  99 // extra space here
                                    6
                                    8
                                    10
                                    12
                                    14
                                    16
                                    18
                                    20
                                    25
                                    30
                                    40
                                    50 ] }
```
            

#### Result

```
System.Exception: cannot determine if synExpr Const (Int32 99, tmp.fsx (4,37--4,39) IsSynthetic=false) is uppercase or lowercase
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Fantomas.CodePrinter.addSpaceBeforeParensInFunCall(SynExpr functionOrMethod, SynExpr arg, Context ctx)
   at Fantomas.CodePrinter.addFirstSpace@3123.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 3127
   at Fantomas.CodePrinter.addFirstSpace@3122-1.Invoke(Context ctx)
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.atIndentLevel@426-6.Invoke(Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 426
   at Fantomas.Context.atIndentLevel(Boolean alsoSetIndent, Int32 level, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 430
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 803
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.atIndentLevel@426-6.Invoke(Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 426
   at Fantomas.Context.atIndentLevel(Boolean alsoSetIndent, Int32 level, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 430
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 803
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 803
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.opt[a](FSharpFunc`2 f', FSharpOption`1 o, FSharpFunc`2 f, Context ctx)
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 546
   at Fantomas.CodePrinter.smallRecordExpr@1343-19.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 1343
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 803
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.expressionExceedsPageWidth(FSharpFunc`2 beforeShort, FSharpFunc`2 afterShort, FSharpFunc`2 beforeLong, FSharpFunc`2 afterLong, FSharpFunc`2 expr, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 914
   at Fantomas.Context.atIndentLevel@426-6.Invoke(Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 426
   at Fantomas.Context.atIndentLevel(Boolean alsoSetIndent, Int32 level, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 430
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 546
   at Fantomas.CodePrinter.genExpr@1622-225.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 1622
   at Fantomas.Context.atIndentLevel@426-6.Invoke(Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 426
   at Fantomas.Context.atIndentLevel(Boolean alsoSetIndent, Int32 level, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 430
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 546
   at Fantomas.CodePrinter.genImpFile@86-6.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 86
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 461
   at Fantomas.CodeFormatterImpl.formatWith(ParsedInput ast, FSharpList`1 defines, FSharpList`1 hashTokens, FormatContext formatContext, FormatConfig config) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 395
   at Fantomas.CodeFormatterImpl.format@409-1.Invoke(Tuple`3[] _arg1) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 411
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104

```
            
#### Problem description
Fantomas throws an exception with an error message that _looks_ unrelated to me. I would expect `fantomas` to remove the extra space. I get a similar exception with

```fsharp
f x = match x with
      | 5 ->
          { actual = 6
             y = x }
```

#### Extra information

- [ ] The formatted result breaks by code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/25/2021 08:33:56 - 9bc785c38d316c5e5b1bbdaeae04ed05b5ee8088

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Theodor, thank you for reporting this issue.

The extra space seems to lead to a function call.
Consider the following [example](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYAHmAC8AHQBOI5BGlhgYKsx4BXWsLAA2cZJk6AnmsEBfLchPc%2B%2B0RKk65C5aqEaTO6ZYFhDkEIaA):
```fsharp
let x =
      { actual = 6
         y = x }

let y =
      { actual = 6
        y = x }
```

matching AST
```fsharp
ImplFile
  (ParsedImplFileInput
     ("tmp.fsx", true, QualifiedNameOfFile Tmp$fsx, [], [],
      [SynModuleOrNamespace
         ([Tmp], false, AnonModule,
          [Let
             (false,
              [Binding
                 (None, NormalBinding, false, false, [],
                  PreXmlDoc ((1,4), FSharp.Compiler.XmlDoc+XmlDocCollector),
                  SynValData
                    (None, SynValInfo ([], SynArgInfo ([], false, None)), None),
                  Named
                    (Wild tmp.fsx (1,4--1,5) IsSynthetic=false, x, false, None,
                     tmp.fsx (1,4--1,5) IsSynthetic=false), None,
                  Record
                    (None, None,
                     [((LongIdentWithDots ([actual], []), true),
                       Some
                         (App
                            (NonAtomic, false,
                             App
                               (NonAtomic, true, Ident op_Equality,
                                App
                                  (NonAtomic, false,
                                   Const
                                     (Int32 6,
                                      tmp.fsx (2,17--2,18) IsSynthetic=false),
                                   Ident y,
                                   tmp.fsx (2,17--3,10) IsSynthetic=false),
                                tmp.fsx (2,17--3,12) IsSynthetic=false), Ident x,
                             tmp.fsx (2,17--3,14) IsSynthetic=false)), None)],
                     tmp.fsx (2,6--3,16) IsSynthetic=false),
                  tmp.fsx (1,4--1,5) IsSynthetic=false,
                  DebugPointAtBinding tmp.fsx (1,0--3,16) IsSynthetic=false)],
              tmp.fsx (1,0--3,16) IsSynthetic=false);
           Let
             (false,
              [Binding
                 (None, NormalBinding, false, false, [],
                  PreXmlDoc ((5,4), FSharp.Compiler.XmlDoc+XmlDocCollector),
                  SynValData
                    (None, SynValInfo ([], SynArgInfo ([], false, None)), None),
                  Named
                    (Wild tmp.fsx (5,4--5,5) IsSynthetic=false, y, false, None,
                     tmp.fsx (5,4--5,5) IsSynthetic=false), None,
                  Record
                    (None, None,
                     [((LongIdentWithDots ([actual], []), true),
                       Some
                         (Const
                            (Int32 6, tmp.fsx (6,17--6,18) IsSynthetic=false)),
                       Some (tmp.fsx (6,19--7,8) IsSynthetic=false, None));
                      ((LongIdentWithDots ([y], []), true), Some (Ident x), None)],
                     tmp.fsx (6,6--7,15) IsSynthetic=false),
                  tmp.fsx (5,4--5,5) IsSynthetic=false,
                  DebugPointAtBinding tmp.fsx (5,0--7,15) IsSynthetic=false)],
              tmp.fsx (5,0--7,15) IsSynthetic=false)], PreXmlDocEmpty, [], None,
          tmp.fsx (1,0--7,15) IsSynthetic=false)], (true, true)))
```

So 
```fsharp
actual = 6
 y = x // with space
```

appears to be a function call and there Fantomas is trying to figure out if it needs a space or not.
An extra pattern match clause in https://github.com/fsprojects/fantomas/blob/9bc785c38d316c5e5b1bbdaeae04ed05b5ee8088/src/Fantomas/CodePrinter.fs#L48-L57

before `UppercaseSynExpr` could solve the problem I think.
Please note that original extra space might end up to something different then you indented.

Are you interested in submitting a PR?

**Comment by theothornhill** [comment]
Thanks for the info. I'll give it a go :)

**Comment by theothornhill** [comment]
Do you have an idea of where to put the tests?

**Comment by nojaf** [comment]
Thank you for your contribution!
