### ISSUE TITLE
With v4.4 an `if [predicate expression] then [action]` fails to correctly format

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#1481]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBBAGwBcBhWAN0QCcAdV9Nl9WAxdMAMoBPPFUTZO3Xv2GjxAOgAiAS0wBzbqOXQ88ukjJYKI5Xkk8%2BgkWOzyAkgHlz0q3NsAlRADMKiaFWVYDnYLGWsFAA1sCmdLWRt5KIp5ABlldABHWLC3ROj5AWgAC3FMbNcEpMSABUwqIslJbAQAV18wOnQvZTUWpjrA-gBeSQhfKkFMRkKS7EwVJjAACjwwNFEmdLUASjAR9ggxxAnu3wAaMDgunr2wPjw%2BxAAxZV8l7caDw-GwbiQ90aHCBXbpqGp1IoCRC%2BfwAUV8uHQVDwSxYkEotAYzHkADVTC1MBRlAAvZhoj5fIEAHwAfIJEBl5FRYGlRIDqXSoYySph4OywMovGA5lRiss-oh5GQqFRNgAjFpiJYRAByOElAHFjmA0RqoTKtngZqUFuSLgJZVt7HgVW0KA4mAB1IrKMQCIgkMB4XYAd1dDUp1PFdouXkJeEQuwAtDT%2BUDDhKpfB4MrpZaFUrVer5FqJrr9QF0GojcUTcpWJALt6KVx43XZS1EHGIFTlphQ%2BHI2AY8345hcYTG2AADxRr29oENpuBw6tpboENgKfRulhigR3tz9tLpiNlcTw79zzNRjvA8QKf8%2BqWEE9ApTUinZBncBQCMGot4VBgADar4goB1pAAAkVBCLw36QOkVCVv%2BhwgfQg7IGgf51hAAAML5oVAdjoEgSICCSz5wUCAAsJFgAAunBAC%2BWGHIB8YgWBEFoFBSKwUBwGIRQjbfqhaEAIz0UBACymAAB5pOgiApHwaj1JxQkAEzoRR1FAnRcGMUCzHgchUByrAsAUEpuncUh-EURAykiUxULYNoJlBNKsJ4Q4XjScR2FrhG6m0XZOnwaB%2BmQUZJlmcFPF8Sh1lgAAzHZunusQiAAELeLATCILU-S4GITCRZOu6IP5mmBRRemsYZxmmUlUAWbxBkCXWpH1RAkApSQGVeFlsmwD6zDQJgEa4fQsDDQEQRFYcU5lYcWlAkFHUhdVkDhXVlWNTFv5xQArO1UBdelmXZQAqgQvBMMNo3oONk2DDNEC%2BaVdYaQtFVcSxBnrbVM0IZZsXYQAbIdnUeidvXZTQFAjXgnQbC0-hZU9YAvfNECLQxW3fWFf31QDTVWdhADsYPHT1fWieIcrMKj6NvQF2k46FbEbf923NXFAAc5MQ5T0POeg9OdhjYBYwBLNrezBOc8TaEAJx86lZBeAVdDYHMqNzYz5XM19rM1RFsvRVz2GCZhcXg6lAuIA5TkUNNh0M-G72Y59TGrT9Mtbab8t1oJwlW8dqsFfbcCO8Lh0667TNLVL3v477gO7ebtlW7h%2BFUA46AACpMEIjr%2BiL66vbHevxwb0tJ1xftA0JiXBxDZBMLALR4Yo0LKI5BXayVYsS2Ay0NbjbHQRzdep0JbVW%2BJEl2F4uclOg8IRgIRRZVQRfwIph2kWpusffrnuj1A48mynLXxoJB2z5JuHdBJDhXXUWWwhJBDZXgeCPYde0H%2BXI%2BlcT6G3YjBC%2BRN64B1BnfCSng4BMHgNvXecV94Dw9uZU%2BYCJ6XzioJMmsD4FZXgLabAtMmAeTsDYL8h1BLoOPpg0B2A2gBCJDJJ4WURQFVzqFCBO0r5AkErzK2RDEGiRYa8dIzxOF1F7mDYomB%2Bj%2BGYAAfT9DvIokB6HAMYWtc%2BydIFTwDkrWBLd%2BhCAdKyLeygNGozQYfd2DDgpYP0bXXB2FVJgznmYzAFimBWNIeQyh1DUZ0IceLDBzimESLYdIpgXDmA8Ignws2aFlJB2wuiJg5jLGmCoOI6gkj2EyJlHTeRRRFHEAKmomxiltHYyrj9VxntJ4CMOMpdOmS544iQmldI8AtjIM0XvABQI3YRKcStFxHEUn%2B3jMpRuXTJJPHbv4QYfS8KDNqcM1BozDjjMHsPKqTSZkGP4XFZSM8lkSUULAKguZ36f3wD-IIQzUb-3qZLRpeNjZnNSXWZSt8ukxKkWlR20AADWaUlEQuOHgHOAh1R0F4tgKOcUXZjLjg0kB1dfluMMW0myMDMkqkQD6WJGUqCDT4EkxAndujoFdIMQw8BqZkOYDQ9FotwmHITj8za%2BLzkeIIZkgA0ogRABAF5Lz4LhRFuAvIlz8jyyJUzQHNPMq0i5wjrnwkcngIobyRmfKHnytmNcWnuLSSYzJhEiy%2BBbr0REW9EBylEggbyaEMX7KxV8nFic8WWoJXFeKltMmUB6OgFZ6A1lBEIhoOojxc6wEznwKgAwnZctLiao5Xt%2BU4ODdheKGS0LomoMwLAARGApCCGoNl5D6XpCZUETlPluWAMcToqJuKBVBqFWheKnTS0FICF5FIOA5TwEwDDWAP8iykvJVIpVZdMUV2xbogNvbNVWrrPFRZpaVB4EwHKXwerTCQiEEiSSy6c1mqgHweAHkvIWiEL4At-bd1XNLW5R9nkl3yKYBQLwWiVWTJHqAn2gr-nxnikC0tFpNj%2BHdUgG9PLXyUXolBPATwf7fnRjRIAA)

#### Code

```fsharp
namespace AltCover

open System
open System.Diagnostics.CodeAnalysis
open System.IO
open System.Reflection
open System.Xml
open System.Xml.Linq
open System.Xml.Schema
open System.Xml.XPath

module Configuration =
  let SaveSchemaDir (s : string) =
    let file, config = ensureFile()

    let node =
      config.XPathSelectElements("AltCover.Visualizer")
      |> Seq.toList
      |> Seq.head
    if match (node.Attribute(XName.Get "GSettingsSchemaDir"), String.IsNullOrWhiteSpace s) with
       | (null, false) ->
           node.Add(XAttribute(XName.Get "GSettingsSchemaDir", s))
           true
       | (a, false) ->
           a.Value <- s
           true
       | (null, true) -> false
       | (a, true) ->
           a.Remove()
           true
    then config.Save file
```
            
#### Error

The online tool at v4 explains
```
    (33,0) (33, 0)Error10parse

    Incomplete structured construct at or before this point in expression
    (21,8) (21, 10)Error589parse

    Incomplete conditional. Expected 'if <expr> then <expr>' or 'if <expr> then <expr> else <expr>'.
```

With the command line tool v4.4 this reduces to the less helpful
```
The following exception occurs while formatting stdin: Fantomas.FormatConfig+FormatException: Formatted content is not valid F# code
   at Fantomas.Extras.FakeHelpers.formatContentInternalAsync@95-5.Invoke(Boolean _arg2) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.Extras\FakeHelpers.fs:line 96
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 405
   at Fantomas.CodeFormatterImpl.isValidFSharpCode@378-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\nojaf\Projects\fantomas\src\Fantomas\CodeFormatterImpl.fs:line 378
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 338
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
   at Program.processSourceString(Boolean isFsiFile, String s, FSharpChoice`2 tw, FormatConfig config) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 113
   at Program.stringToFile@312(Boolean force, Boolean profile, String s, String outFile, FormatConfig config) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 326
Formatted content is not valid F# code
```

At master, the online tool throws a missing method exception instead

```fsharp
System.MissingMethodException: Method not found: 'FSharp.Compiler.SourceCodeServices.FSharpDiagnosticOptions FSharp.Compiler.SourceCodeServices.FSharpParsingOptions.get_ErrorSeverityOptions()'.
   at Fantomas.Extras.FakeHelpers.createParsingOptionsFromFile(String fileName)
   at FantomasOnlineLatest.Server.FormatCode.format(String fileName, String code, FormatConfig config) in /home/runner/work/fantomas-tools/fantomas-tools/src/server/FantomasOnlinePreview/FormatCode.fs:line 57
   at FantomasOnline.Server.Shared.Http.formatResponse@80-4.Invoke(Unit unitVar) in /home/runner/work/fantomas-tools/fantomas-tools/src/server/FantomasOnline.Shared/Http.fs:line 80
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

#### Problem description

See above

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 02/25/2021 13:38:25 - 9b676332b04b7d14dd55d9b46761c56e9c6eaf1a

Default Fantomas configuration

**Comment by SteveGilham** [comment]
Adding parentheses as a hint around the predicate expression is a work-round in this case.

**Comment by nojaf** [comment]
Hello Steve, thank you for reporting this issue.
The online tool was recently updated and should behave better.
The problem here is that Fantomas puts the `then` keyword right after the match expression.
