### ISSUE TITLE
hash define with elseif

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1527]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiAlgMzAEQFEAhAVQHEAdAJwoDsIIAKASmrvUQBsBnRHMALIEAEm3oMWYjj0RgxDMJJq0OteDkgAacFF4AXPZloBzbqjABtHRFAKIkACR6AngAdkaSEb1brDRwBuAIacAK4eln4KAAzadv4AkmqItHoAypgAXshx8WAALFFgALp%2BAL65NkWOLu7mXqm%2B8YEh4eZWeWAAjJV2kAJBAB4AMkaIwynGegAWTXldAEzRRaUKFX62fU5uEZAARrCwnHMKLWERHXkLvadpiAC2mHCcsLQAgnoEagDy2KO0OSKEGwIV4K3KvU2p22dU8ByOJ38DmC53aQLAAGYbv40q4gtBEERENhYFREAAFIJUIL3RB6RBUREKPRUcLgtaQ6ow3bw47Ys5tNCXeL5bH2XH4wnE0njWAAdwZ0CCvCSAVgSsMryZDBZbPiqwY6wUUKRtR5hz5XJRgsinQArGKoBKCUSSWSSK53FQlSraGqNZgtY6QTJ2YbOc1ufVedqBRd0QA2R2QZ1St2IADCnGV3Azr24uugelJ2uBoMQYYgRoYJvsUbhFtjyNa8c6AHZk6nXTKBA89gzS2AQ2D9RCNlyzdHG-zm6iheiABydvEu6VkvMvWiD4cV0cc8eRycNhEz62tvIATmXkre2HpVDz93uQUHut3dgNVYjWyPUBjp5bNFOi6WJ0RTFc0xlO5HmeIN0R3SswGrKpDx2KcTytQD52AnowNTW972gp4jjgzo30Q5CwFrKB6z-adMLnW15muMCkiQVJvloAAVKhnAAdUwGZt3LCjv2hX99noyMzyA%2BYsTwiC3ioWBQjUPAuEwR571fVl3wUT8kLE000M8bwmxk7D5lFMCBkGBJsC46YUgIGQ0mmUk9AE%2BAhMdfJlj3cMDx-EyoDMgDGOFOwugdGyhiSbBMEGb4vSCYsqAIQZXDJbhuEDLdHTtfyPzHY0JxChofHCm1IoULok1iwYACVEDgKh4C8nz0T80SgvE8qwoY6r0S6DsGua1r4AAOVCe5%2ByoX4Enpe4zEdLoetK1DYSge5Qk4QxODGAAxUlnwMBkuLQqrz3iLolzA8bSXgARdv2o6TtS7Tk2gaYqXxe8AH05UwbzZnWmsyq2irzKwpibqvBqlOpZxvioUYCw62ZfKK-SSvBzbdgG6SYZqhglmTWzEaCZHUcwAtptmhkFqWlbhrBlDgshna9swA6AWOqhTvvC66iu2T4gWXDOkgSnqbRvRnu53nEH5wWBy%2Bn7qSLBlAeBoS2aoiGCcaUXLPFlipdsgA1FsiCMdQTAxwduoCr9euMyHCa2CzYbsBZ5ItoZDtUos8tttQjGMR2sf16ian643Buu33rIDwY8FgPQyDpDKssQHK8qj9FCpjw30MtImIvRBYYotl6ebGIgXmgABrIhNebuluE4tIaUzI4Zvy%2BCRJdwy3brCT-0TsXffqqXJsQOUlaJPQFRSYXEHUhLaEEvK3jUXsGaoFnOgQkfKNj2jJIwiuhs6BZRqlgBpRBEFcezHJSJIe9pf5ARP4fir7g2hzI2lUp6m19ndVOLlHjcGmIXToztAGBWAX1SGk8b5JwUAseGUsMgmE4IgJSxgZopE8ogPYAgEB-zyKfZBrtUHu3NNfL2xN0QYlAlLN4B1jC0CDrQEOrwMi8NSqEMkXFYBsTIalPKwlQxnyMuPcqGDWGV06BiSWeRpZ7QZLQGRARZQmAPnNTeRgd75jkSOeho9GFKPQVJVRt88gYnNlohWhhf7DBpHseAQQsywFyiYeei8xiWL0gwAy59S7HnLo4rBDAMT%2By0XgWmQQ9iEJgbTaYaRnCpCGGEku%2BN6gpHgL8X%2BaQXCEOhmo5xKctFfFKX8UJX0qCcGwJAQpICy7VKcfEDENctEVKoE8eW1CClnx0MUXIXhuCHVyuYBCZQgA)

#### Code

```fsharp
#if DEBUG
    ()
#elseif MEH
    ()
#else 
    ()
#endif
```
            

#### Error

```fsharp
Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (3,6)-(3,12) parse error Expected single line comment or end of line;
  tmp.fsx (5,1)-(5,7) parse error #endif required for #else in implementation file|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = ["DEBUG"]
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@75-2.Invoke(FSharpParseFileResults _arg2) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 81
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@451-4.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\src\fsharp\service\service.fs:line 451
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

I guess bad merge of all results.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/18/2021 09:01:39 - 2022e157942246d9c51abb3956343f966a9dec38

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
There is no `#elseif` in the F# language.
