### ISSUE TITLE
Fantomas throws an exception with custom operator (>??)

### ISSUE THREAD

**Issue by josh-degraw** [fsprojects/fantomas#1533]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYCyBLAdrgLYCGANmHEmAC4AWJNY8uAzgA5kkCertdiMACdYsJrABm-QW1YBXRCgA6QpfjKImBMgUEAKAHwB%2BIwEowADzABeS2AOXIAGnBRWmmgQDmrVGADarhCgEKFQACQ03OzIaJAENM5BoZDhAG7kCn6BYWEADC65KQCS%2BEj4NADKuABeyIVFYAAsyRAAuskAvg3BrRFRMX7xFUlFqRlkWWg5jQCMPbmQ2CQWADK6q4j4XvSjcwBMeX0dYd3JIYuR0bFQAEaiZHth45k3M0X7C8%2BViES4cGRYPgAII0ACiZQA8hJ1vh6n0IBJyO5jl0FhdnldBnF7rBHl8IhMpgEEWAAMwEiCQSrsEjQRAAIUQElgQkQAAUSEISERNIghE9cjQhApUad0X1UgMbpBcfjJelXtlSU1KVAaXTGczWYhVrAAO786AkdylNKwY2eIGCsLC0VFE6hM5hDEpLEyuU2wlK6akgCsauptPpTJZbIAquwYkJjab8ObLbhrWqkWQUQ60ecFdKhp6CS9Jm9SQA2QMakPatkAYS4rFYVaBrDt0BorK9iORiDFTolY3duYeXoLxPeuQA7GXg1qw4hsL9bvz22BU%2Bnco6IM7Qq6qf2cYP84rC8rGmAAByTzWhnUNwH4JcrrsZ8VZvs5vd4oeHkekgCcF-pwISDQ-INkQpBLnaj5rpmLrZtcA4fgeRJFieswFKSQaXpWiA-H8ALJqSD7dhuvaXG%2Bdz7gqyHHnM8wYeWiCAcBQi4f8eIESekHEWAm69K%2B8HvvKfbUb6qGfBhpTlDQkL4AAKkI3AAOq4LsKadtxvFgNu-QCRRiFUT6JKoRS9FTsCIhyGUAAiiA6H8zEQSKUFhOuPGkZi5HDIkSGGaOYSzKqGHLBYxQSLJAj4GCaY4XQrI0Mp8CqSqRxPj2L5kbpXmfiJRlzAGQUrKUEi4BYkLRowrJghY7BsnWSZ3mqfopdBz6wfx2JQAk2W%2BaSsylgVFgAEqIHAQjwAlSUnk0zUuTBW5wR1WU%2BUeolzBOA3DaN8AAHJyEQC5CNCxTAUQvhqrMGnuW6nlEHIZCeDocIAGKsqQNDMbJ8HLd%2BqHnhhm2svA2B3Q9ugvUIb0OYG0AMNyLb8gA%2BvquCJXQkCXelHmZV130oXMf4DeZ3LcJCQjrE2E1o2q00Y21GWLTjBkrblHzoSeSwrETPCk%2BTNC7ft-JHSdZ29bT83tTKt33bgj2IODkP8p9gy4zRHx0ezXMk2TbA0MD0uy-LjBQxhMNcnSzFIyjuxi3x9Myozwk9Se%2BziezwUAGqvAyBAsNslNLjTqUkZj13YyMKurR8JluysT2WS29Xe2U3j%2B9TM2hK5mnaVKYfeUzP2NPsgUxxYVliAA4poVU1YgdVAqn-rp%2B0c221ji15vneMfPlbsgzLugMoC0AANYMnDw%2BaKwMmVDyiA3ntDWEepQduSHO6eR3jvM35oT7P17PbYg%2Bqy0yNCGlsSuIDZxWEFaIJlHOAtCCLJ5ESvWcLR6lFbwXHzrezABpRAiB2ChXClsUoM9eSwnhK-ZeLU0p0zbvbcOndVa5H2H9EuUU-isDoA3KaTcwCZyuuvTKm9Lg5R3hAfYBN2bVG2BocyXg9pbHiogW42AECwMaG-BBwckGh3bt-ShTtGhkjZo0SAwIdBeHwHHfACcgTVDkYwOQbJZKwEkmwxg9V7zwNmq1cWdsEJCVEdvUkZJ1ZSJkcxfAui0i6iBF4R%2BB1r4EBUvVF%2BvCDEZxblpT%2BpjuoWJPGSV2Ui9aeBgasHktx4AkBrLAVg3hD7H10Po6KNsAkSyCRHFmuQyTRykVZNgJBbgaBwWwOglRuAVBWBk1chjEHGOQUMLY8BoQwMqFEDQwTf4FOLlIiEHSYTpOhkIMgEh0bv1ITpYR%2Bkf5dwKT3KRQCQHaIqKUMeJBFFUyXpkmZa85lfwWeY-pYQyT7ykd0oQ-xdbcIac5PxpxXBtAaPEVgT1kl%2BCIp0IAA)

#### Code

```fsharp
// Minimal code that displays the root of the issue:
let inline (>??) x = x > x
```

#### Error

```fsharp
System.Exception: was not expecting token QMARK_QMARK
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Fantomas.TokenParser.getTriviaNodesFromTokens@1069.Invoke(Token t) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/TokenParser.fs:line 1071
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 241
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 251
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 75
   at Fantomas.Trivia.collectTrivia(FSharpFunc`2 mkRange, FSharpList`1 tokens, ParsedInput ast) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Trivia.fs:line 524
   at Fantomas.Context.Context.Create(FormatConfig config, FSharpList`1 defines, String fileName, FSharpList`1 hashTokens, String content, FSharpOption`1 maybeAst) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 200
   at Fantomas.CodeFormatterImpl.formatWith(ParsedInput ast, FSharpList`1 defines, FSharpList`1 hashTokens, FormatContext formatContext, FormatConfig config) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 387
   at Fantomas.CodeFormatterImpl.format@401-1.Invoke(Tuple`3[] _arg1) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 403
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

I have some custom operators that end in `??` (used for testing). When trying to format the file that defines these operators, fantomas throws the above exception. I've verified that it's not just the fact that the operator includes `??`, because the following operators seem to not have any issues when using the online tool to test:

```fsharp
// No issues encountered with any of the following operators:
let inline (=??) x = //...
let inline (<>??) x = //...
let inline (<??) x = //...
let inline (>=??) x = //...
let inline (<=??) x = //...
```

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [x] The formatter fails to process the input file

#### Options

Fantomas Master at 03/22/2021 19:47:45 - 8eec950c7d7c431bb251fc0156e405763642923c

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Josh, thank you for reporting this issue.
I was going to explain how to solve this, but the fix was rather simple so it's on the house.
Please check my PR in case you ever encounter any similar problems in the future.
