### ISSUE TITLE
Trivia before SynPat.Paren

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1753]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAZUQQwBtF4A%2BAXQB0AnCgOwBcBPAB0TAFk9GAjRAIQCuASwJIqYABQBKMAF5qdBbQgQA9Ko6YA5ABUSYAFSTdYALT722gKokZ5zVptKAxEIBmYACIBRPlYDiSipgALaIIbziAPpRAHR8QrTwLogEAM6IQSphEYjiiQSJbDHxick0tM6ISe5ZwRASAG6EAogANGDcZXlgaCb2jmCwzPRCsLQyfVZDI2PK8hX1KgDys%2BOxXUmd3eLNBK1KkG3gUBn0o7QA5mmoYOgnEKBLkAAkTKy3kIn0Rw8qr3tWrd7ksIAAGY6gqAASSS1Xo2CEAC9kJDQQAWP4QMh-AC%2BaMeWKgbxYyDQXwYv2eL0BZLuRIgAEYCfVIJwAB4AGSKnOql3oAAsqaDGQAmMFEnHBfF-J6skkfcncWCwAjC4IAlp0kGg0UsjW4EJCOAEcYAQXo3iSyzc3NoqIZYDchAykrxLLlGoVdMgytV6v%2BNK1wMdAGZ9f9sMw8NB%2BIg3LAqIgAAp4Kh4ML0PIB4L0KitN3Sj1E17vH1%2BtURzX7bWO9ERiCQKMxuMJpOc2AAdzy0DwGVhjVgvdG4xzKjzBaWUpUMuCnsDZc%2BFbH1aBaB1SwArA2oM3Y3x44nEFZmKwqL3%2B7RB8O5mOIM70ohCzPi9TF0qVZWS0GayGoQA2Hcm2jfdDyTABhAg%2BzScDxjSCdoHoRM7ydF0nynd1ZW-d8oGXKsfzXekoQAdiAvdWyPdhwkiFCH1dDCiywt9SSXT8VwI2soQADjIkCKIg1VRx3Oj0PqacIFnFR50bb1WP9fDaT-UEAE5eJbM03CzKhYJCEI8BQidROCcSwEkwlmMVXC2IU4N10dRkIUdYCWwPNtEENY1BNoWi0OfCTX3lHDfWs79FLsqFGWZJzyI0rSPJNITHUMvzTICr0grw0LbKIkU9Sc2EkAYZZaB0KhGAAdSEQUfMfFKzLAaTiQykLqTCnKlkZcNor4s0qFgAQkk8VIhCNLSDPzIyVBM%2BrGtLFjyW%2Bdi2o3epGXrJyOWhNwdAFapvEfbABUTehKvgaqd3RCUGJfJjAvmqBFps39wpFbcNrwdlYTcIR2VWPI8CQqhvHZZgkzSNJbx3TcrrEzC52w%2B6KR%2BJ7CJW4JGUA972QAJUQOAqHgU7zrrGHjLhqSEcspGluytGVEZUisdx-H4AAOQEXIqBtaEsxCG4d0ZOq0oXRGQgEAhRkKe0ADFEz0848h0FiUc4kUeKc5nE3gdhxclopZaoeWxqA6ABTTGMtKiTshDOoUhdu9LEcerLnva1bVKx3r00YZYqG5eCiaFC7Sam8nzLuqnnda2nHXFICOS9rhff9%2Bh2c57nef5%2Bz7fhiyfTFiWRH1uWAa0pWPhVpSllFKKoUgROfb9oR4J1wupcQA2jezE2zfTRC8itm3qpzim88%2BKP5WW2O8rrjkADUtQSGorkDlDLpH8PHcjylK5e6uutnj7pYGxC5iX%2BBEkuVfg43hrKZ9CevSnqFRXWw-2U8WB6H8RBLRBsGIbjGvo6aGt9ZqyQ-PJF2qNY5vVnrrIu9o%2BCmmgAAaz4H3VBv80jFWwBmRAsF9ghG8sJXy11-IOxFlTTK0dXZ0wgKKTGddWaIE7O3A89BuzVHLogIa31aBVTmGaJIVFOZZyhCJMB985JfloTAl%2BjM64AGlECIGYFtHa1RYR4LCHaB0EiyGw0YrnCOD8d7QNVtXdW799pGjSAKYBUJ17kNSpQmSzUoFyMsfUUUHs66IiuEQXqlwObwnKogbg7AED6NBJIlxM1pGQNkZPGOUJQyOTrmaQolxaDH1oKfcYiIckAwEEmHQsACrwgBpDR0cSjE3RMVvcsLUUl0LDLXUE9cJZ5FoNUxoiAOxXFEZEPhiRBFwRqvRepFDGlUOaZ41p8jQShhnp01uow9GcgzNweAeBIKwAhlcFhbCiiTMmtiMOd8x5JJpm0tJB9OmeGbngbgRBbHNwFNgRgDAPpnKkdcqA1R4A2j0dgJgRBblLKWKGN%2BnSrTAttKck2VACBuEgP80xMjIXeOCKGOBnSVFqMqQwWEGC8D5KDrUwxZNjGj0xTc3ebtcVMM6cg8lqC9FpF6v1JILD4LEHWYgxAwNQaIHBnMcRoJkrxOFu4xGNDFk4pUKGRRnSwVUGNPQKJSA-nxJOGQNEXw0jSwhrcSRuIgA)

#### Code

```fsharp
[<Sealed>]
type MaybeBuilder () =
    // M<'T> * ('T -> M<'U>) -> M<'U>
#if DEBUG
    member __.Bind
#else
    member inline __.Bind
#endif
        (value, binder : 'T -> 'U option) : 'U option =
        Option.bind binder value

```
            

#### Error

```fsharp
System.Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back togheter. Please raise an issue at https://github.com/fsprojects/fantomas/issues.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Fantomas.String.merge(String newline, String a, String b) in /workspace/.deps/fantomas/src/Fantomas/Utils.fs:line 69
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 233
   at Fantomas.CodeFormatterImpl.format@406-1.Invoke(Tuple`3[] _arg1) in /workspace/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 415
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at FantomasOnline.Server.Shared.Http.formatResponse@95-6.Invoke(Unit unitVar0) in /workspace/src/server/FantomasOnline.Shared/Http.fs:line 95
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
```
            
#### Problem description

Gut feeling: the trivia attached to the ` SynPat.Paren` is probably not printed.

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 05/25/2021 10:30:08 - b4ccb7b876b418b62e5392cd821fb750b6919d77

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Related:
```fsharp
type MaybeBuilder () =
    member inline __.Bind
// meh
        (value, binder : 'T -> 'U option) : 'U option =
        Option.bind binder value

```
