### ISSUE TITLE
`mod` name in signature file fails in latest fantomas

### ISSUE THREAD

**Issue by pbiggar** [fsprojects/fantomas#1960]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAGgDoB2pAbgIY5gAGtm89aALmALQB8YbXPkAGnBQAzohYsAliQDmI1GADawiKAjqoAEhYBPAA7I0kaS0Er1kTVRxZDS8xoAMQjRsgBJEkhIsAypIAvZBdXCAAWBzAAXXMAXxDVSMtdAwVjHzNQy2tbBWVQiABGBNdIAFlKAA8AGWlEasRZFgALTILCgCZHSJiNePM1Uu19O0gAI1hYHDa3K2pctHyCjpK3X0R0STgcWBIAQRYAUS8AeQAzWpJgyIgz6jEeuJLB2ZTRiamZizmbOyXQgDMqwsvj0lGgiAAQogzrAAE6IAAKlDhlHQ4kQcK%2BGhYcNsjz6zySw1SRg%2B02B2XmfxuYDCwIgkFB4KhMPh9VgAHdMdBKGJPORYLypLtsepcfjQr11P0NC9vm80uSxVTfnlaQBWBlQZkQ6GwhEAVT0BjhvP5JEFwskou1dxwDylTwGxMVZMmFOJORpBTAADZtUywXq2QiAMI4PkiMO7EQS6AseFi273RAEmVErIk94elU-Bb2X0AdkDutZBsQZQ2Y0xybA9sdrmlEFl6nljOzStzlPzPoKAA5S8Hy%2ByYzsSHWG2mnYSXVm3VBlT3verfQBOIcsvZnFiYmPodCUOsS6dN51y10jLufZfU1ftZy0oMs-Xs9abba22lT9MtzNDBdxm7L070WWlCmKJ8y23Xc4XfLYpi-X0T1-MBW0Secr3dG8QLVMDfU6QNPG8FgThIAAVOEdAAdUkFpJ1TVD0LAdstEApdcILf5XEKIEoOHPY4VgLAvAAEUQHBJE2WDjzxU8NGbND-1eLCoBMPMV3w9p6SfCpKncM5yOaRpDgdRBfGaeEWFo%2BB6O1MJuhnDM5wA1T0lMW88MLdotV0qpPDOSRKhOU1KETOFDkqPQEREEQbQnbUNUcs9ZwvTDSTUjJPK48CAz8yoACVEDgOF4BsuzaQcpjlIVNz1OyvtQkKEt8qKkr4AAOSwdAazhc53F3dB5G1QpqpclSMsgdBcCkSSrgAMXhQ8JExcirwa%2B8msHJ82vheAyhmyQ5sQRa4WWmTA2gZoUXBWCAH1OUkWzWjGtLXMm%2BrOManiN3ywTUR0E44VqONytaezkoU8820vD6sq%2BzbXC6QM9P%2ByhAeByQ4y6nrMX6wbhvA16YfS0ZppwWa6lO87VvWhGtNCDpIN9SA0YxkGWAOimjqppawoup8rpuhNMQep76OJjD3tGT6s007zGZWfKADVqUhaR4GkGQwbrftIfURTmNY5I6vhuXQIVpG%2BJZvT5pEhN4vVrwtZ1iHJZY2GZbNoZ5e4jQOh0m2qlE2AWAAcXESLosQWL4tdzV9YgQ2ao7djgPNry-fUDpfJtw7jshHZoAAa0hVES-EEQyN8NFEDHbqEu-RinL-cbasmjiM5y30OjylmOsQTkC-EblGjWgxxMCkg6PivYvCrXG4UJ30fxbpS29TtzO59i2s4gDoWpZgBpRBED0AyjMaTwa-RS5rhX5uUuct6Jq9jz6ct-3tqDypTM2ERmjx19FVNeRtPbXk9F3b6-tfos38LIPAgkZDdUaNZRAYwygIHvgUVeT9W4v3bjmHCUDEYaABI%2BFmexJIyBIHbEgDtdj%2BBoWFLACJyKwGIqgsK8UGJmXdsbTs2FIE70zrSAEzMCiswppiEg3DyAclkAvXqk9pAz1jLwxsUNUok2lhAjSu8xFKzztzO%2B1Q0RjHgJQCMsA4qyAHkPOoGj5IG2hlLV%2BeiNoM1cACa2kjRJY0oGMPAf8sbNF8DoHwVQnH8PAUYRo8Bzh318LoPA%2BjRG%2BgBIHSRxwEkXEcZdOEOAziQBiaTDxH895gABLnSRJ8z6cJ8J4MulB6Hgybnw0BKc2Jb3TiI7uBQAR90kYXFpxc74iEEsJLwA84yIH2vnOoUcYpxXUdqFCnSN7dI7r02YvsxGH2GSiV8CJ-EiGgHCKS0gwpzMNNPXY4loCRlRCKRuD8Ol4PXgQze2ziF9OgeoAE39JHJIuQmTBSBomgOEFEEIxgRDzTigoFCsQgA)

#### Code

```fsharp
module X

val ``mod``: t -> t -> t
```
            

#### Result

```fsharp
module X

val mod: t -> t -> t

```
            
#### Problem description

When using the latest version of Fantomas, there is an error formatting one of my files. In the online tool I get this error:

```
(3,4) (3, 7)Error10parse
Unexpected infix operator in value signature. Expected identifier, '(', '(*)' or other token.
```

Fantomas cli fails with this error:

<details>
<code>
The following exception occurs while formatting stdin: Fantomas.FormatConfig+FormatException: Formatted content is not valid F# code
   at Fantomas.Extras.FakeHelpers.formatContentInternalAsync@89-5.Invoke(Boolean _arg2) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.Extras\FakeHelpers.fs:line 90
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 464
   at Fantomas.CodeFormatterImpl.isValidFSharpCode@374-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\nojaf\Projects\fantomas\src\Fantomas\CodeFormatterImpl.fs:line 374
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 391
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1044
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1070
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1365
   at Program.processSourceString(Boolean isFsiFile, String s, FSharpChoice`2 tw, FormatConfig config) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 117
   at Program.stringToFile@347(Boolean force, Boolean profile, String s, String outFile, FormatConfig config) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 359
Formatted content is not valid F# code
</code>
</details>

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.

#### Options

Fantomas 4.6 branch at 11/03/2021 17:27:28 - 10f599c2d2cdeddcfb2c00b915aaf45b3a5f9be1

Default Fantomas configuration

*Signature file*

**Comment by nojaf** [comment]
Hey Paul, thanks for reporting this. This feels related to https://github.com/dotnet/fsharp/issues/12303.
I'll try and verify this later today.

**Comment by pbiggar** [comment]
Thanks!
