### ISSUE TITLE
code using mix of #if and parentheses doesn't parse after formatting

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#1989]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAsgDoBORAdqRXgC5gBmAFAJRgC8V5E3PvEAlvTABDMDQAWiLo04BiQWAAiAUQBCAVQDinPrt0KARmMlcAwrHIBnWHgB0AdRL8aiGZGUkSsEgDEcwgHNbYLAiSGY5KXhBOQUVDW0yLj0UgSEjCSkwaEjyaPodVJSWQqLuVkgAGnAoS0QaGn5yAMtUMABtGohQPkgAEhoATwAHZDRIJpoqru5%2BgDdhHCwxjpmeAAZqvUgASTypGgBlfgAvZC3dABY1sABdGYBfC%2B6b-qHRtonyKefZvoWlitOnoAIy-HiQAjCAAeABkmohYVIAhJpqCAEzrG73HhPGY9XhvEYrSAGWA2NGE-6LZZtYG6dHg2aHRDofhwHAWACCNGUeQA8vR4eRzjcIPRFnVsY9fgSIQNiZ8yRSmfMaUCxWAAMxMiCQQ7DYTQRCqRD0byIAAKwhIwnQ9UQJEpfBoJGW0txsteCo%2B42VOGdfwBtLQ9L4l11UANRpNZotsNgAHdHdBhHU9nNYKnGhZAzxXe6%2BDjuHieHK-u8Sf681BqYC6ZqAKyR-WG42m80kRDqYajEip9PkTPZ-i5yMSnBSosy-HeytK8kB1V1kOrPQANhb0fbca7pn8lks5isBegNG8NfFksQHpLXt6Pqri5ravroc1AHYt23Y53EARWQMR1LwYa9bwgUtuHLPVHwXFVvWDDU9AADm-GMOwtcxOXIECJynXhiwg%2B8qXnP1n2XRCGz0ABONDjS5egXBIcx0HQYQQILG9p09WcH1IqBqwo9UqN0EFNk1Vt0N3RAWTZDkx01PCuIImcyznRUyPgh9KPfUEwQk7dEAYpjZPZGwFL0TjwLASCXj4jSBPIhDhN00TGQkvYkG%2BflyAAFRIQZ7GccRcLA7i714kiHNJJztJctdRJ1Ayfy5LwsDyRREBwfg2SYji3WUnhCJs4j5X4r4fmct8Er4EEIwkqFoR2ehfJMZRJxk8RvBoIL4FRSNLixcKiMisrosmF8VyQ0TmwamE9nofhoX5PthHPEhlGhYYu0PUccMjRshpUni1Ps30oAmoTqrDXgQU3OboQAJUQOASHgXr%2Bs1QbrNssBoNrcrLqq1cbp4EEvwe57XvgAA5LB0CAkhBR2Fx0FaSMQR%2B0qK2i9BcEabKRR8bw2IaR1fMVK6Qc1EFUIkqHvHgAh8f4QnEGJkhSbyltoHEG0jSYgB9RN%2BD6kKsdGnHzoqyadJq27aIe1LbUGfkSHhSwetFz69G%2B4aSslmDAe%2BWX4tB7hMRbRrleEVX1f4TW4YRx1kdR9GaYl06oulvGcAJhEOa58nKeB6a%2BHRfTthtu2NZoZm-dZgOSbW7mJN5-mz0dYXtfF-Xfv%2BolpaBuLrs1dF3O2RqADV1VUJpomaD6QsjZCjqK1SoPUouTapsPeHRJLK5hHx0rPPa67yJoAibkC9eOiKvbG7vKpL6m9HReqh%2BhRRYBoTR6k27bEF2iwZ4OtvuGK-Ou6fLSqTl82IHRWbK5ZtnVE5aAAGtVFtb-6ksD5Q4dpEBYXhvtRSYV54jUXlLW%2BS5Q4iXDvdbYMNECJnfvUZMUgKajEyotcgzg9pcjyABZ2JB3Z6CUp7TuZ14Gm1LuvCG2wADSiBEDDGaq1KQexgH2mFKKKhUD24nVod7Ekxd75mzLnTLe7U2SWHEGfL6F8IBX2xkbaKglEGuXDorbYxxmh4FSgEeGBx7CIAMAQBAgjdDULzhogGWjYpSMYboLU4ko7ZQCOQEe5Ax4WGOD4taWAuy%2BVgJ5A4a09qhQ6jQuy4i4IINXn3HgWpI66EgFyP2jpyDRLmIiCwAQyGI3wU0IhFhKF2OEZfDuCSl70N7kg3gWoK6ZPjo0ARsI7QGHgMIfcsBLBTzQRghEsT8IiIXmIhpSSGFr3cYPTJigHbCAMHgeRDtxCHEGN8GE4zCq1NEfUuBnwoiCgEYcIYeA5mpO4FqTemS%2BTwHOWMnmJAcD0EgPEv6N9ZlNN0S0l%2BmS2EcMid8PYv9hD%2BObpAuJDjDZOOltolJzS0koMyR-KFX8BGWFSrAdKsNj4uCZm-BEh8dpDMqflQs0CDawM0Uilx8oH6ai1MwjFNoMJdmWZYaATg2R5OJeoQhFhMrQH8LaHMEChFwtpdfOhfydHyzSbIzJlynBnmsUgfZP0ai3AuBMSwPghltGoQ8IAA)

#### Code

```fsharp
module M

let f() =
                if a then (
#if DEBUG
                    if b then Console.Write("ErrorFlag... ")
#endif
#if DEBUG
                    if b then c
#endif
                    ()
                ) 
```
            

#### Error

```fsharp
Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (12,9)-(12,10) parse error Unexpected symbol '(' in expression;
  tmp.fsx (12,11)-(12,12) parse error Unexpected symbol ')' in if/then/else expression. Expected incomplete structured construct at or before this point or other token.;
  tmp.fsx (13,1)-(13,1) parse error Incomplete structured construct at or before this point in binding. Expected incomplete structured construct at or before this point or other token.;
  tmp.fsx (3,1)-(3,4) parse error Incomplete value or function definition. If this is in an expression, the body of the expression must be indented to the same column as the 'let' keyword.;
  tmp.fsx (13,1)-(13,1) parse error Incomplete structured construct at or before this point in implementation file|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = ["DEBUG"]
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  LangVersionText = "preview"
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = true }
   at Fantomas.CodeFormatterImpl.parse@75-2.Invoke(FSharpParseFileResults _arg2) in /app/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 81
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 464
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at FantomasOnline.Server.Shared.Http.formatResponse@98-17.Invoke(Unit unitVar0) in /app/src/server/FantomasOnline.Shared/Http.fs:line 98
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 11/24/2021 18:43:36 - 9eb1365627a87929af770bd60baed8be76e61103

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Formatted output:
```
module M

let f () =
    if a then
        (
#if DEBUG
         if b then Console.Write("ErrorFlag... ")
#endif
#if DEBUG
         if b then c
#endif
        ())
```
