### ISSUE TITLE
Cons pattern in `let` bindings is converted to invalid code

### ISSUE THREAD

**Issue by clkbug** [fsprojects/fantomas#1996]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPFKAnmALxgDaADALqQA04UAztlgJYB2A5k6hYxFARhUACRZCAB2RpInLPQHDIogG4BDdAFcZ-ESMoN9ygJIckHLAGU2AL2RHjYACxKI1JQF9Hgt2InSfHKWisYqGtq65H4QAIw%2B%2BpAAsuq4ADKciGmI3FgAFqFOsQBMlH4eIt5KQoniUrqQAEawsOiFIuGaOnzRTmDFCR1WiAC2bHDosBwAglgAouYA8gBmGRwOMWDLmizlXgk1HXWBss2t7cpqXVGbAMyDylaS6tCIAEKIy7AATogACupvuoRthEN8LiIsN8dHtKgc-CoAg0zm0Hp1Ij1Ns4HhBIE8Xu9Pj8srAAO5g6DqFhmVSwSnsKYQ4RQmHGCrCKoiQ6XJFBFFM9HdNC9JwAVhxUHxrw%2BX1%2BAFVJNJvpTqRxafS2IyJdt0Ls2ftqgjjsiWqijREhXonAA2CV457Som-ADC6CpTGdUyYLOgWB%2BTIgOr1%2BnZEE5wm5uONfNNAquGOFmwA7HapYTZYgkqNGmCA1sdohYRz4WFo6dY2j45aRcYAByph3p4meyYcPNBwv6uGG0u88vnSsWm59ACcDYJ02WWDBnpGI3UeZZnZDBq5Rr7UH5g%2BumL6sUMm3tBJlxOGYwmWs2HaLYZLtQ3TQr5p3ib38UPacn0%2B%2BZ-GrUvfRLjeYDhr4vb1DGA7PgmVrGCUdpmBYWCLBwAAq3yEAA6mw%2BTtgWwGgWAkb%2BBB-ZmqWQ67kU9wfo20zfLAWjmAAIog6BsGM36LtCy4iKGIF3kcD7yHGlGvkU2KHikuAmMsqF5Dkcy6ogVh5D8WDYfAuESs4ZRdsWPb3qRUAiduME1vosTilJqRmMsbC4IsSrqH63xzLgki-EwTCam2EqinpK7dmu4EnCZIRmdWmyxLaNm4AASogcDfPAmnaVigV8auEbrsZwQKJFw5FCmcWJcl8AAHJaCMObfCsJjTiMvASrEBGCTyeUjFo6DsOx6wAGI-POWDfqhEGFVRcH1oeZU-PASTdb1mSDd8w1cXa0B5ICLzfgA%2BqSbBaQUbWGUJeWmdBUV7mOcX0UChCLN8GTemlBQ6Zlwj8YRxGIudEWXUVxilHa0l3eoD1PWw3pVTVYL1Y1zXRSdIVGWFkBdT1bB9YgK1rWCY2BBN4lA%2B%2BfSQGDEPPVgC2Y9juMueth6bdtvpgvth24cjOWhQ0F0US%2BsH6MUAxxQAatcbycPAnBcK9ea1h97jZWBqO8-9-PmZsxQ0WT0n9Uxvq%2BZL5gy3L71cyrZ1o3ztRiYLIjFJJuupMxsBYAA4tg7meYg3m%2BWbmwBRbRG5WjW4A5NQvWbri1Y5kbyTNAADWbxAsn2BMChVjAogLbVX5V74fpt6nR1YdPhrV1OMUsVkxViCktjHxYOSOQE4grH2RwOG%2BdM5hZrD3yI3017FwJpdRg%2B4eV4DQslWTADSiCIJIsnyTkZjZyCawbCPRdBQZKNW2rBUR8TQvTc7uBKWMTB5AHfS6cHP1lpuFe2wLFkOzdZM2NwmD0S4NVHIGlECNCSAgXeThR4HxLkfMuJooIz0jiIW4B4ybTHYlwDg%2BsOCGymDYbBLktC-FQrARCICXK%2BTwspZ%2BodEHkQ-prPotxSZOHJj1MEHAqGqBJNwAetVO6cB7l6GhwYsrBW5qrSCjCjh2y-sIW4IsY6Yx3mkYEjR4DqFdLAHy3B66N0yGI3in1lYhx5jI0Sn87g63YcxKG6hGiYBvlDPIVhCCWFSMYuhFjZA5HgCsHeVgJCYCscwpwtwnbsIWAE1YRiNrfHQMsSAPjpFkTCVXYwtxo7sKXivChlgzCp3UHgt6hdaFj2%2BvQyxRN7aKNruwhOJSk47yYPRRi5h67ekQPNWO2NvZeR8qIiUQFKntUnnlaeTDMn6FuPPRpgITy-HsUwaA3wOKcBcj0uU3cpisWgG6IEDIC57wqbA8e8CJnlyQdM2eqDL7sOCes30ECkDeMqYwagjg5BMH6j5Pg15PBAA)

#### Code

```fsharp
let x::y = [0]
```
            

#### Result

```fsharp
let (::) x, y = [ 0 ]

```
            
#### Problem description

After formatting, fantomas output the following error:

```
The following exception occurs while formatting stdin: Fantomas.FormatConfig+FormatException: Formatted content is not valid F# code
   at Fantomas.Extras.FakeHelpers.formatContentInternalAsync@95-5.Invoke(Boolean _arg2) in C:\Users\fverdonck\Projects\fantomas\src\Fantomas.Extras\FakeHelpers.fs:line 96
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at Fantomas.CodeFormatterImpl.isValidFSharpCode@377-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\fverdonck\Projects\fantomas\src\Fantomas\CodeFormatterImpl.fs:line 377
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870   
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
   at Program.processSourceString(Boolean isFsiFile, String s, FSharpChoice`2 tw, FormatConfig config) in C:\Users\fverdonck\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 114
   at Program.stringToFile@346(Boolean force, Boolean profile, String s, String outFile, FormatConfig config) in C:\Users\fverdonck\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 358
Formatted content is not valid F# code
```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 12/04/2021 18:09:39 - 9e35634e25acd50cb0353abd4b7cd5cf0fc07792

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello @clkbug, thank you for reporting this issue.
This is an interesting case from an AST point of view.

@dsyme I believe this is a case where the `PreIdent` would be useful.
If you have:
```fsharp
let x::y = [0]
let op_ColonColon x y = [0]
```
leads to
```fsharp
LongIdent (LongIdentWithDots ([op_ColonColon], []), None, None, ... )
LongIdent (LongIdentWithDots ([op_ColonColon], []), None, None, ... )
```
So, inside the pattern node, having the original syntax would be beneficial.
And when we detect the `::` we should treat it as a special case in Fantomas.

**Comment by auduchinok** [comment]
It'd likely be easier to work with `::` if it was a separate pattern case, but it would probably require a lot of changes across the compiler.

**Comment by nojaf** [comment]
No, the AST got updated and [SynPat.ListCons](https://fsprojects.github.io/fantomas/reference/fsharp-compiler-syntax-synpat.html#ListCons) got introduced to represent this.

To close this issue properly, it would be great to include a regression test. That way, we can make sure that the changes made to the AST and the new `SynPat.ListCons` don't cause any unexpected issues or bugs.

If you're up for it, would you be interested in sending a PR (pull request)? It would be awesome to have your contribution to this fix!
