### ISSUE TITLE
"cannot determine if synExpr Paren" when Lambda after If expression

### ISSUE THREAD

**Issue by jindraivanek** [fsprojects/fantomas#2015]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAKAlgMzAFwCcBXRfAC0QDsxtZYxEAbAZ1IHM6BKMdbI6gPpgAtAD4wAFgBMnADqVIAGnBRWePJkptmqMAG0VEUBBNQAJHgCeAB2RpImvEsMnIZgG4BDRiV0HTpgAMygGuAJKUSJR4AMqYAF7IIaGSLhAAui4AvslGaeZWtroO0c6hbl4%2Bdvr5EACMuQGQALKeAB4AMpqIHVRseGRlKXVSgfmZpjkuxk0WNtWQVPAA8thdlIgxVoxJ%2BRXevmj%2BKVKNppAAopGr67spUIzYkOPZjTPnc0X2AEZ0jEMfSqHGr3ADMZ3ClFYBDwADFNN4AHKIADujG6AIChBIL0mbz2nwWv1g-wh%2ByqflqkghEEgMUQAFtMHBGLBKABBPBXFZrDE0mjeVi4kxTUzvVyE4rE0kEoHVY6hACs-Lp1k80EQACFELQCIgAAqeAieBmIPCIAiY0zYxDCiCikzi2mSn5-K3mOWU%2B4ANhVMTVGu1up6sBRFugnlYEXcsAjGjZ7ogNrtYAdeXKLqg0vd5OBCoCAHY-QGtTrYHqAKrWWwECNRygxuOYBP87CC22hCYi-EZwpEt1kjwHeVUgAcxfVpeDAGFGJHmNO2cxsdA8OXEwKWB2Al37T3Zn2pQPZcOvSkAJwTwNlvXNRnfC0bttblNpsBOgrzI8knNDilHKk6mCKlVUnINy0QRdWQUVt21ffcPkPV0f0HT0APuOoGhA-1J3ZbBzQIRcGQZTwN2TTtXmmAkkKzY8MzQkFhlObCS3AvV6SZFkWypZ8hQovEqN7L9kJlejT3Q4ZwRY3D8ItDjmRJbj7nIndKLFajhNolCT3-RjQjqCQVQiKI8GWSgABUCEsAB1TABifOD%2BO7QSD00yBs1Q8S9ICOplWkjV2QIWB%2BHgAARJhMCZAiyOIbdTF3VMEIlGiSicTzdPzUw6l9EDWjaMJsHMihKAuLcYjIcs8Fs%2BB7P5CQxicvcXMQtzHF-BjMpMOoi1y9oImwTA2mWGtPDXAgLjaaw9WYZhmxgqlFQa1SBPUoSvigNr0rzQDx16toACVEDgAh4Gq2qqXq%2BDmuS1rSi2kcMMvPbDuO%2BBESIBkHwIVYwnNBkdH5OortW1z1sgBkiEYDR0Q2WFyxI9QLXMr97rPUJRhVF7y3gZpIeh7o4YIBHopVaAyCNdUCIEFFMBqwZgcdDSwc2nTtvuKQsPuFp2kC41LGWAgumXM7Bjqpb4rUxm1oWFmxIyqkpGYrm8t5zx%2BcFzBl3ez6LR%2Bv6AcAhn01BhYIahzAYcQQniaRlHWYek4pK51X1aFvBcfNy3rdGkmQLJinVwtanafso33yZmW7vttGAikQy9oANWHTVNHgTQ2BFjdR3FkwErfD83BS2XZg6hW-OV9pYX4Vc5pTyJ08zsWw4LzNUvarzOogKQcortpQtgPAAHEzQmqbEBmubG4WnOMkl42WrBjzo4k9GeuVvGLe6TVWWgABrTVjT3s1mDMmITUgkkPvm%2B5eLi3O5-D6Xv1EkuO4V3aueRNEt7NMMqGR2w4UBqUDsnNdkkQ7w6wIAbG%2BjllrORBgvfs2k5ZsxOE9LmABpRAiBrAFSKlQCIZ9TS3Aci%2BRqiVrrOiLlHVBDtQigmAr3UqTJmBkCnvcS6FD84R2fu3eWYJOYpDpOnHYgU2AfSoFVRA3xmgIDuCkW%2BzdeEiX4WghhSthHsnRGwSgVdKA1zZHEXRo0iB6nMrAYyUjRpzTIXxeBTVEE3UXnRV%2BAiUigidloqGFpKA2PcCGLQkCvpAM0KApcdi76zxWlLE2fDUYrwCKCeO69za3A6Cab48BPCzlgLNLQX9LaROUU-VRCTvKmFBOXYRoVNaeG%2BDsFhmsyAxEsNEdoxTuFJWoW5JedCY6VJ7sI7BuCrHRAiAfTwBjRY8TgRLGJ89nHIJfoCN%2BYI17CO3lM3etxmCBWCpEZEy5EA4w3pbUe01ZoRP5CpeZCDYlIPicvCpJhQQf02UaNiiBanMGgAQSKCJzTwArCAtk4VoBzmNPGa%2Bii5n3wWY-OJZTnmdzAKCDBwitj-NXHIpAnSHGphUOkZIDhmCwlmroJRWQgA)

#### Code

```fsharp
(if true then foo else goo) (fun _ -> 42)

```

#### Error

```fsharp
System.Exception: cannot determine if synExpr Paren
  (IfThenElse
     (tmp.fsx (1,1--1,3), false, Const (Bool true, tmp.fsx (1,4--1,8)),
      tmp.fsx (1,9--1,13), Ident foo, Some tmp.fsx (1,18--1,22),
      Some (Ident goo), Yes tmp.fsx (1,1--1,13), false, tmp.fsx (1,1--1,13),
      tmp.fsx (1,1--1,26)), tmp.fsx (1,0--1,1), Some tmp.fsx (1,26--1,27),
   tmp.fsx (1,0--1,27)) is uppercase or lowercase
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.CodePrinter.sepSpaceAfterFunctionName@2074.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 2074
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 879
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 607
   at Fantomas.CodePrinter.genImpFile@96-6.Invoke(Context ctx) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodePrinter.fs:line 96
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/Context.fs:line 502
   at Fantomas.CodeFormatterImpl.formatWith(ParsedInput ast, FSharpList`1 defines, FSharpList`1 hashTokens, FormatContext formatContext, FormatConfig config) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 388
   at Fantomas.CodeFormatterImpl.mapping@408-1.Invoke(Unit unitVar) in /home/runner/work/fantomas-tools/fantomas-tools/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 408
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 446
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
```
            
#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas 4.6 branch at 1/1/1990

Default Fantomas configuration

**Comment by nojaf** [comment]
This happens as well with `(foo) (fun _ -> 42)`, I believe the `Paren(Lambda _)` might be relevant here.

**Comment by nojaf** [comment]
As `(if true then foo else goo) (42)` does seem to work.
