### ISSUE TITLE
Unexpected expression: Fixed

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/fantomas#2112]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBXAzosAHALgE5gC8YAZgJYAei8Y8Ahvo5ADThTb76UB2Ac0yowAbU4RQEaVAAk%2BAJ65kaSP3zsJ0yLIBujADboVYrTIAMHGTMgBJPkj74AypQBeyK9YgAWM2ABdLQBfL0l-HUVlETUnTW8dfSMTcW8IAEYw60gAWUZqABl%2BRALEQXwAC3i09IAmc38gmVCtKWz5JRNIMvgAeXIivkRnRQNPCL1DYxFUtNqsmwBRB37B8bSoA3JIRpCstpsO6NUAI1hYA2rDpOm0We8AZgXte2xCfAAxfkMAOUQAdwMxSu1iIxl2zX2EyiXTOFxBEESUxS-l8z0RzkQAFtKHADLA%2BABBfDLPoDYHoiiGbAQ6QtGQHbRHWHnS7PJHJGaosAAVkpkGcuEY0EQACFEORYIREAAFRiERhYxD4RCEBHSMGIWkQenSRmI5kxOFsiY3FEbABs-MFwrFEqlJVg-1V0EY2Hsulgrt4BPVEE12rAuvCCUNp1Z6o5t1MGwA7NahSLxZLpQBVXDKQiu918T3eyi%2Bynkala7xNOlQ0Mwo0R9mTTl3bkADgTtuTDoAwgY3ZgOwTMGDoPgpX6qQYaWW9q1oZ0a-C62auRsAJytpP26U5bEnVWj4vj0vWcs6yvtavh%2Bem5FLmqWbkCxN2lOIPv4vh7kuB4NgfVyc9QY1I3raN7msdJMnvG0RUJcgVUIPssSxVhKQDSdIWnKtZwvE1Q0XRsNjqNcnwdTEcTxQtuX3CcjynBkZ2OADayvBsYxqJ5IMfGC4NI3ELgojZUJo9C6MwhjIEAhdr3wmofH5exHHwXo%2BAAFUIBQAHVKEqD8Dy-U9Dn-cSmNwqTWO8dI%2BQ421CUIWB0AcAARRAgRxODR0EmRjyDfSmUM9QgLwsywKte88moWxyGUioykWA9nAqKV8E0%2BBtMpHwGjQisMLPLCoH8ySWNAmR0njUL8nsKhqF6TNmClRZqFwaVMEwAt30pHkMqErKRJysT8uYkDuXSFsyuoAAlRA4EIeBktS7l0r07KDNy2INAKwaCNXUaJqm%2BAfnQLEd0IfpbBVLFhEpdJFp65axKxdADF4IEhg%2BKUkJ4VVlNndbzTmO8NkgHapXgHIHqe4pXsId63P5aAKnlYU4IAfX%2BSgUqqa69Xorp%2BpMwruVqCCAbCmyFQUXpCCKAdZqqNLOs82isdEnG4h%2Bm9vFqeZRtJxhycpygB32w7VROs6LqGzGQ16rp7seyhnsQSHoc%2B76Bt%2Bjn2IBnm%2Bap-BQblhWleYGH7zhhGh1VFG0e0yWf2xmJcfaQKiukWpZNGgA1ZFRX4eB%2BAEGnRybenpC879f0iFbHeuUyXYgWpLOJ-IPnsodWp9hx-cDunbYjsM8tZtX2esWoQqT6gHNgfAAHFlXqxrEGa1rs%2B5Drc-t7CAtjgnSuJsH5eKUV8WgABrUUFVH5VMCU5xFRfC4DrayjP0yk8lt8laJKL6SOZGgG-kBQflWdMovuUJyqD4LTWsJBwt2FwhxY2KjDwZ4SmeluccKd7uNlqLaAYAGlECIFwBFKKZR7CzyVGsHS1E37dQ-rdFma1t5BRkA8f6aRcj5FijiTAFQW4bAWqvby68DSGS3njDaaQHhE2wa4QQYwbICAOmUJKiATg5AQOsNIL927My-l3fGGwHhcy1kCAQfAU58DTgSVwUjmDoGlMpWA8l2HMFanA1%2BodGZS2QUItmO9rAPE1tgwkj1VR8E0boR0gh75HQvvwa%2B-ZtECM-p3Ix6DpAPHdn3OWawCiKhOEwLssAWqCAPgrNxpDw4d0Ypeah6sTGJ2wQ5AWjAThjDwQLCozgFBOHyDErqa8bobzElQn%2BIjaFl2wcA0B6inD2HHowWRtNl66ViT5Chm9jJVJoY8Xu2Ch6tJHmsTANk7IOD%2BAOOg%2BtwZDHrk1FqriUKEHBF08hf5emJP6ckjBe9hnynbNKdJmBoCEEoDiaxKp4CpivgSJy0BuwKh9EvZ%2BK8SlkLKT0ipfSY7VMeAAhhRBcR6x4cUhBOpOABC8GoTAHwWoiH4cEIAA)

#### Code

```fsharp
use ptr = fixed data
```
            

#### Error

```fsharp
System.Exception: Unexpected expression: Fixed (Ident data, tmp.fsx (1,10--1,20))
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.CodePrinter.genExpr(ASTContext astContext, SynExpr synExpr, Context ctx) in /_//src/Fantomas/CodePrinter.fs:line 2664
   at Fantomas.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /_//src/Fantomas/Context.fs:line 852
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas/Context.fs:line 476
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas/Context.fs:line 476
   at Fantomas.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /_//src/Fantomas/Context.fs:line 581
   at Fantomas.CodePrinter.genImpFile@94-5.Invoke(Context ctx) in /_//src/Fantomas/CodePrinter.fs:line 94
   at Fantomas.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas/Context.fs:line 476
   at Fantomas.CodeFormatterImpl.formatWith(ParsedInput ast, FSharpList`1 defines, FSharpList`1 hashTokens, FormatContext formatContext, FormatConfig config) in /_//src/Fantomas/CodeFormatterImpl.fs:line 384
   at Fantomas.CodeFormatterImpl.format@403-3.Invoke(Unit unitVar) in /_//src/Fantomas/CodeFormatterImpl.fs:line 403
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 446
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Sergey, thank you for reporting this issue.

I believe we don't support the https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html#Fixed expression.

We can probably add this to https://github.com/fsprojects/fantomas/blob/ab3b477bfca5c5d67960b841aa2dda46313eb790/src/Fantomas/SourceParser.fs#L572-L587 similar to the other expressions.

Are you interested in submitting a PR for this?

**Comment by sergey-tihon** [comment]
Here is bigger real work code sample with `fixed`keyword
```fsharp
type BufferObject<'TDataType when 'TDataType : unmanaged>
    (gl:GL, data:'TDataType[], bufferType:BufferTargetARB) as self =

    let handle = gl.GenBuffer()
    do  self.Bind()
        use ptr = fixed data
        let size = unativeint <| (data.Length * sizeof<'TDataType>)
        gl.BufferData(bufferType, size , NativePtr.toVoidPtr ptr, BufferUsageARB.StaticDraw)

    member _.Bind() = gl.BindBuffer(bufferType, handle) 
    interface IDisposable with
        member this.Dispose() = gl.DeleteBuffer(handle)
```

**Comment by sergey-tihon** [comment]
@nojaf should I close this issue now or you do it during release ?

**Comment by nojaf** [comment]
Ah, usually, these get closed automatically when they are merged to the master branch.
Your PR text didn't use a linked keyword, see https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#pull-request-title
and https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by nojaf** [comment]
Oh yeah and let me know if you want a release for this one.

**Comment by sergey-tihon** [comment]
No rush with it, so it can go with your usual release cycle
