### ISSUE TITLE
Can't format fragment of source code with #if element, `and` keyword, and triple-slash comment

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#2359]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwAVfAFwB11bsEBXAG1IAUAnAS2y8q4Bu%2BMAF5aECJQCeBUgCFmsaAGsAEoi4BzABaVR4iYYA%2BYBUrUade2ADMwjLukoBmAExhaBiAHpfYAFT%2BACL40NwE-LDogV5gvt6x8WAAjABsAEZ8YByIzJj8QmDpiipg2pa69niI8GA2sBxgAAYA8mwA%2BgDCAMoAak1gJcp4ADSJft2OJGBtXX1gmMyKAO5gUcxSRUNg6IzY6YiNtmAADGAAfmCpAKzXztcjYFlceGB4mDaI495glLDZVG40D0jj%2Bv3K2Uw6E0pDw2EWrEalG0UNMQ3UWl0tAAxFw7ABCABysCCAFU8ABBPDdSgcRjAvCxADaAB4aXTgQA%2BAC6OMQ6HgeNiUNqZhUGKsLRsNmqlDS%2BnQhmMaPMEt0UpliDlqTWdgcTjSnnQkBG4Cgsv40LwqDATLNEFASqgABJpLIbZBQSb7RJIM6BItGMg0HanRATqaw1AAJIC-mUSYAL2QkbDABYfRBuT6AL6ph2Zl1u4NQL3533%2BwMl0Nh5LlwyQACymAAHgAZRyINv8zTI71R5KuE6F7OGPM%2Bx1Kv3Fj38%2BBSjvoRA0qSsftTyvMIM2mtO1z130AUQFC8766dkGYNkgI9z5cnDddMhLkHSsFgzHPFYDW%2BrhYgzgHhAkCxtUHCUAAYo4iyEogyzMGeQG-HSiC3mO96FtOz4em%2BH5fsBm7biG-5gGmSGQN0RAkHIiD1DkbCYBwOBaoc%2BESLSQZoRI46GA%2BFYzmgr7vp%2BB5%2Bj%2BRG2iRDwkRRVGIDRdFdrAyyHNAmDVLGAhKPkXBRGxkgoVxEA8RIfEEQJUC4SJmGEX%2BUapORlHEPJtENIgpIELIHBqRp6BaWpkTGkhNiLNURlgCZBYXk%2B7qCVZbFiVWO4kQA7I5ckKW5nR5HgeCdFEeAccCDT6XUoWoU6o7cRh0UWUJeGibZyVRgAHOlzmZTkjaIPsrHBeV4WRWAZlFthcXCQlTXEVGACc7XUa5OT5YoQUkSFzBhZVd4TjZdXxY14l2bWEYyU5JAUjYlCHPl2DwqVHEVUqVXGTVG57RNB1JdNtZ1qdGWLcuPVcHAK2letm1PdtvG7WNlkfTZh3NbW%2B5-c5F1XRw3RAyDelIQ9g2vY%2B70NQjX2SQOgGo%2BdHCwIwAohAhvAY-dhlbehO21bDnpOJNiPfU6yRkTJzYttGNhkOU6DdNoDSUAA6lw8B9khw5s9VHNvVzZak7%2BSMC9JUZNq2YsS-yh4bcuMvgQrSvaKVaaq5D7PQ5zsWljzn26-zSppORIuxjYXAti0Xn5A0h4tgQOS5bpq1RtcjuGM9EWE-xWsezrEm7j7aXC62ABKiBwBw8A28rJEOwTGtE%2BnlC82T2eGMkbV5y2hfF-AhJ7AcHBStGV3YNaSHJFXLua27kDYCw-AIUuEENPClAY2Q2Ge1nJHJHNMntw08CNtPXCz4g88cIvzPkdAKJMcChztMsit9qPpkwxP2vRXz5NhkOfuthSHBMVIFoHAOyFTLnbJClc1YvWrmnV%2BGd34NxIq4X6hsRZ-wAUAkBlAu69V7jYfuPUh4byflFceL4p7MBnp2E%2BZ9Dgr3dGvI6e4UaG3QZgQBwCXiUH3pQw%2B1CF75HPjJS%2BjFiAYzvg-O2JDhovxfG-DcH9G4SFcJTVBrZehVjkI4QU0IwGlRaonCQychojSwnAuujC9ZKlcELNRLYIJ02BLHLRApHCaD0RAwxWYobP1dnI%2BBCjEFRlcAbMMRsWxBFgJQAA4lqCOUd8B4Fjh4qSXiwDGNTuZLm%2B1M5MOsQ5YWB8j5imUHIa%2BygtR4BaFLZiy09hxzDODR6ScfGkJrhPHJCCvafz3LnQ2sF4KdhopQFS-J6GIBCIHdAfBY4UgFN1XBRCoxNOkaYmKL5OmBO6UoiArgW6sIQpodADj0BOKiJMI5%2BRGA5DILAWMSAnA6VxmtAaUCU4wKyR0%2BGXT17BK3gcjGWAChKWhAsnukzHAzIKmDV5Tt1Zj3aRs75WzflhmcCdVBB9FxdhwOkeAmBsqwCSdCAZR8YUW1WbInCyLHyKJIs4FBYT4mHB4PGRYABpRAiACD3PjLGMpUJL7kohi052viyHUpJj8vJhg3DkQUFCZQ2LKQ0zpp3KgNQeFUKXPE6OSToV41ZnC6BCLYFIqlSimVEhnCqLCXIRinUJkvDCDwaCV14CkmmVEEI0A8hMUCsK5pRjWkyL8ZK6y0qrGytsUyyOLLcCPOYOyWmhU6QEBXGufqFK3kmKpYJeRtKglotCReTl3KRY4J7lKBV6AlWdiWcdNJGSPmjS%2BRawt2z6UFMNuyYG3CEAphedm41EUzTclTJ6PAEEkk2hWTmIAA)

#### Code

```fsharp
namespace Test

module Primitives =
    type BlockHeight =
        | BlockHeight of uint32 

    /// **Description**
    ///
    /// 16bit relative block height used for `OP_CSV` locks,
    /// Since OP_CSV allow only block number of 0 ~ 65535, it is safe
    /// to restrict into the range smaller than BlockHeight
#if !NoDUsAsStructs
    [<Struct>]
#endif
    and BlockHeightOffset16 =
        | BlockHeightOffset16 of uint16


```
            

#### Error

```fsharp
Fantomas.Core.FormatConfig+FormatException: Parsing failed with errors: [{ Severity = Error
   SubCategory = "parse"
   Range = Some tmp.fsx (15,4--15,7)
   ErrorNumber = Some 10
   Message = "Unexpected keyword 'and' in definition" };
 { Severity = Info
   SubCategory = "parse"
   Range = None
   ErrorNumber = None
   Message = "XML comment is not placed on a valid language element." }]
   at Fantomas.Core.CodeFormatterImpl.parse@43-6.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 51
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 447
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-07-11T16:44:40Z - 98a7449918c2167c0478a151ec89bbde826a74c0

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by knocte** [comment]
My bad, the [<Struct>] attrib needs to go after the `and`.
