### ISSUE TITLE
Support new Interface Static Methods syntax

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2500]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAwgBaLQDWAcogO4DKAngHYAuAhgB4A6ATp4z3whgA9MMIlyYZkVbMwnSAAdusRYm7N6CsK0bx5kAOaJmAfTDoTRBNriMAzs26sAli3s7u%2BO-ZdIv%2Bjiwhi7QrDg49GCIAI5YLgBu4YgsAoxCYHhybjhu%2BABmprRszKEACipqGvQAPADkACpg1CTpjWBoABSOsqEWiOgARupgxb3QFarqmmhuzACUYAB8nYuzLGAAvGCNAHRjpROV01q8-GcZWWA5eWCFB6EAslYI9U0tKTtNXT2H-UMjB7QZ7SBDrOQAWiW1xYixWaxhcm2eyBIOs8E6AGZ5mk0pcTDDcowCqZ7CYiiVysdqm9mq0vh0wN1KdB-sNuKMWZMqjNEc0XNIwGSFstVlsvrthRTxtyTlicWc8UIrjdiXdTABJBxsRjQRBo17tD5tb5MywAjlanq6-UveDgsBQxFwzrsNCNBFzcXsXZWnV6g0Y7G4i7KgmqkkAGRShmktONDK65vZYGjjFjRHBLrdX0W2x9aYzIcEYeyjCJJKlhbjRvp7STAxT1czfOoAqIQpM2fdDTzYB9VZj0nlxfSpcJt0KGuYA3jddNnWTI2nAwdTsc3Dchn5guMIpWOY93t2e81M-QI7OkAANOAoMLSun7KgwABtO8QUAZCCQAAkmjUF9IDmG8PyEP8khwLBkDQd9vyEAAGW94J-LUkBYWgXAAL2QZCUIAFjAiAAF0wIAXzwz8iKgf96EAtBgJYUD4Ig8JoJfOCUIARko79IEeDhIzyZtmO4gAmBDqNIjIKLAr8%2BNo%2BioBSeAAHl8iE4linoPBRIyVioJgt9qIgMTeP0gBRPR1M03CTKgHB8kgKTyN4%2BT9MUozIEGWBYBwPTwN-SD2Ng%2BzMXM8CrWmAAxNxwioagKwCjInGglyZLc6i-wAryfL85KaOCozOPg-CIp-WhFFYPUACFEHyWAvDKVhnEsGduAKiBUsQdKhFkjJ3MCnKgLy-yIoMkLjJQsAAFZyqgSrqsQOqGq8SNYGodQwjJLUElgMJSlgRhOqkbg0vg6S%2BsyljPJG3yxqyoK2OK%2ByADZ5sgRbavqxrEAAVUUKptsQXb9t6I6TvycIyV6iB%2BqEQaf1uhjRoKiaXumgB2D6vuWn6vAIHBWHsewCCOjcsGgZhGsh6Geou1y5Me4aUfutGnsMjj7IADhxqrvtW20LVpnAYYZjKmZulmoFR8aOcmkrvwATj5paVt%2BsmgmO%2BaodF%2Bnv0uuHroU6XvLZuWiq56auKQ%2BzPv5xAAEF8nasn0HQVgTu62GwHhqipbo3Lzcey3Qutni7dx9WvFoAZQj8iGdbpn2-bARGaNN2WQ%2Beq3xNVvVnfa2P0HjrWvbO-WMkN33jY8zPg5u0Opu48LI4dx2VCwPQABFEFyEv2vL86DcZgbmcDoCQItnOw%2B4sq7YE9gNXyBpWloawNAAdT8aQTsk8Wrslk2J4Yqfs852f4K4uaF44ZfV5SCy9fXxrmG3%2BBd-m1795HiWx4DpSjFmDsyborDIXF3q3yXowfILh2CqSqLIRqFl2DKEQCTFwiceY-yrqPBG49AFn0bjPZuV9sZQIAEqkEavAd%2Bn97L4RwUIauqd07ZRPlAIhClQH2S4rzSh1DuDwAoFgC06kVzoGfPNLiKda5DQ4ZAdAuBSgVmio1D2zB2oNAntPC%2BpDvxcRVnbKhcAhGPGUS4VR6jZCDw%2BtAGQzgqbqFMG2D%2BRBnIHyNkfOuCiuEeR4dNCSH1F4d2cPQVS3AhKODoe4%2Ba3MmEkTwf7Y%2BhCmK6IVvZMSEdpr8Q4KE1g4TIkuEcCIsR%2BQJFSN4bI7x8jAFKJwCovIajuAaK0To8%2BGTAlmTtvkwpUTmDmIaZYpp1jNHqBOjABx1V2ouJ3u46p-8UleT8YFAJKExKtxyYvAAas9Gqbh4BbhiSdeJCz8EAOWWkjpGN1nzy2RwaKXcqaYMYPsvQRy5knUYWc5JPjUnAPSTc%2BCYkb73PYN3WAzAADiJgUFoIwUdY5cSElgBYXIpG9d8qAtzsCyBWyLEVhqkEcgNVHFkBMPYVSjBaCsEsJrUR2t7K6zFr-Q%2Biy-lByxdcnF34xLkJyQlQlJhNopG0WoXusDGACheY7PQzwLSVOmt7TxNcakYoUVnYheiwFCDEvwnJjtciGEYI83Uh1qUuGNbILAXgGiwDQikSkWDprMsrswpJacCGcoelqzp6yjEGoaeoRgvQEiIHWumeV7IJVuGleTEWLLcF-3OUsu6XLfVAu-JiW2%2BKhm2UjLSwY8BWCE1gL4dMgq8gJrdYk5NvzanepASQnVEBMTZJQpAOF6gXCWBYOEAA0ogRAigHUsC1KS3Q9jq0-M9RctNPruHNrCt0nJRLdBkFsvYDusAu7CPQTOeAgzGnEjhV4BFDgh41tRR6thyMZYN0XdqsKmyO01RatHRA3dinQE3CXENB6-pSqOr3aARNnDmunSq1hXr51NqfdNTEdyO1dt-Y68IxRO4U0UNpXSSc9YztvabFZSM1nwUxKCjtg7h2L1KeydSa7GAbryIq7iCEUVorVRnDVD7-FLoQ3ijtGHQgDIQHZF1ycoN3mInhYC9hoq%2BBfK6kAZEgA)

#### Code

```fsharp
module CheckNewSyntax

   // Check that "property" and "get_ method" constraints are considered logically equivalent
    let inline f_StaticProperty<'T when 'T : (static member StaticProperty: int) >() : int = 'T.StaticProperty

    let inline f_StaticMethod<'T when 'T : (static member StaticMethod: int -> int) >() : int = 'T.StaticMethod(3)

    let inline f_set_StaticProperty<'T when 'T : (static member StaticProperty: int with set) >() = 'T.set_StaticProperty(3)

    let inline f_InstanceMethod<'T when 'T : (member InstanceMethod: int -> int) >(x: 'T) : int = x.InstanceMethod(3)

    let inline f_Length<'T when 'T : (member Length: int) >(x: 'T) = x.Length

    let inline f_set_Length<'T when 'T : (member Length: int with set) >(x: 'T) = x.set_Length(3)

    let inline f_Item<'T when 'T : (member Item: int -> string with get) >(x: 'T) = x.get_Item(3)

```
            

#### Error

```fsharp
Fantomas.Core.FormatConfig+FormatException: Parsing failed with errors: [{ Severity = Error
   SubCategory = "parse"
   Range = Some tmp.fsx (4,93--4,94)
   ErrorNumber = Some 10
   Message = "Unexpected quote symbol in binding" };
 { Severity = Error
   SubCategory = "parse"
   Range = Some tmp.fsx (6,96--6,97)
   ErrorNumber = Some 10
   Message = "Unexpected quote symbol in binding" };
 { Severity = Error
   SubCategory = "parse"
   Range = Some tmp.fsx (8,100--8,101)
   ErrorNumber = Some 10
   Message = "Unexpected quote symbol in binding" }]
   at Fantomas.Core.CodeFormatterImpl.parse@28.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 33
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 447
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```
            
#### Problem description

The changes of https://github.com/dotnet/fsharp/pull/13119 introduced some new syntax. Fantomas needs to be updated in order to deal with this properly.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-11T16:37:09Z - 7fb34e52debe65604158a2a9730a5d8927a47d9f

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
This was somewhat addressed in https://github.com/fsprojects/fantomas/pull/2510.
