### ISSUE TITLE
Fails to format when using (* comment *)

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#2745]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnAhgG6Jhq5YBOAlgHYDmYAtAHxgDyFSFYsADllVg0mrDlxFgAgrgCeNaAB4ArjSpZWAXgA6FLcLAAKAFR58AWxJwkYfLhsAjWMTBGAlDr0QAPqwDuagAsAFQp8GgJoASEAMQpYMwBhIRoAZUpIABpwKFxsAXpcVDAAbWyIUAhKqAASLBleZDRIWixMssrIasJ8dCVGkvaqgAYsqqrIAEkaJBosFKoAL2RRsYgAFkGwAF12gF8V8s3Ouoai5tm21c7u3v7S1YgARgOxyABZfAAPABlaRG-EPQsAFLg9HgAmIabHZVfbtCqvWr1fqQQHwNgAM1%2BNEQaRkmFB4y6PT6RXuD3BL3GAFFppjsctNhBIOgMZBoXsXgiiScUY5YOhCR1ibcyUywABmKkdKa5ChYaK0HoAOUQvnQfyFVUofQ5sK5RyRpya-MF0uuJLu4rW0uZKV4%2BGgiAAQogMbAKIgAAr4UIWLCIChayo6xB6ypwqrc4W8s6m4MW0VocmrACstqg9sdLrdHv%2BsF8gegtkQU0IsGLURowYgofDEEjlWjzKNfNgAoTItJyfFADYM5As07Xe7PQBVXgNCjF3Jliv4Ks1sAYnq5etgRuHK6tuPts2Gm7dgYPMAAdgHQ5zo8QCXQtlwSXCOsiHqXK-Qa9WMIjBu3sZNe6doeVongAHBeDrDrmnpvIgZj2IGb6rmGX6cvChr-lA8bml2IEPAAnBB2YjnmSToEISEfihYzfg2v6IphkDYQelpiiejwjOKg6QYgkgYgGFBJGYZj4Eudaofq6F-siu4djhwFsWCzxcZeJGeikcFUHA5HVhm76fjRaFRhhMkAXJLFJseYKUipPF8QJGlmFpAoURm4mGZJxnScaWGAfJrE9uxUq2dmkhxCo8AACKIBqTkCWJFC6hJP5SQxplQC0QEBVZqyPDaXEfJ8EwYkEASAikAQelgADqVDwMCS5QsldGpTy6XnK0-mWSmYyPOmBVfMVpWAtSVEVVVtX1SCGa9k1HkpV5aU%2BR1WXdeKjz9gNRU0BiVCfGwU4Lh61KfLwnq4Lggi6eKoFzVUtEbvRbXLZlXVHj1VSPOeW0AEqIHAnCTQ1GZrHdlQPZuYDNjUjGvRZ73reBv3-R68DKko8GBpiEwBmYhQZo866Q9DxztWYSjoAIGo4tEHoiVgAlBDJb14blhFcX9APwG8FNU38tMUPT8UDtAAS%2Bo6AkAPr%2BFN7LNY9rUxu1cPbgpgUUpxJ7vF8YWhDIHC-OQQPTTdYMQBDT1Ky9Fws4pqzgspWuFbr%2BD6xQhtYOjmMUNjuP4%2BtROWy2jHk5TVDU4gAtC4GTOnLb6v2zZWsu27Hs82HEdRwuwtcaL4uRIG0t1Q1geK8Hys2-DrNjOCwVO18ABqlrOrQ8C0HQxtLrdpeLc9KIq4ias5TX%2BX1580QqJEV0t9M7edyDZvbEZTYmdbnVV3bNf9WPkWwFgADi2AnWdiAXVd8%2Bmz3K-eW25mq9lH2VOCm1a6q6p-K6WCFoCseINFu2qCrJIaYsFvb%2BxPO5e6y8txLVvvue%2Ba0Tzgm%2BsnDUdAaAT3kFWeY6CFxKE9EEWAUwZhYAXFdSiBkoGeWvrA2S8DB4P3FOCJGqCBI0DIcQb4Qg6CgIQhQf%2BtA1BXXAQ8fS1EqELRoX3Ohq0EZIPZk7XmVAGTfHMPYeA%2BBbywEuvQN%2BEcKHiPBtAqGq84GyOrlUCUmsHiQGPoGKgFhZg9AANKIEQLwYhgIsBTGdKEeQJsTxiKvjA6RZl6FEiHo-CAEpHY2OdHeGgABrBkuAwqwAiqqcgiBuZKIjsfc6l0hAiNWJAox1CQlWzMfHYelik5xN9GpP%2BVBcDQGoE5dhAZ4BjlUEIaK0A7yhEXHpZCwSTE3zOKHPmOJfGOkSdgPEBJqlRMlHXGx6cpkulCNAOZcw6iLK4ogU69jHGkPQJLcg4ULlKF4HLeaLVe6VLOAPCJjCTwSlHjY1x7jCpez4ZieJYRkl-GKWMCUoySY7jCeYzeljt42LSNQSIbwECMkCSM%2BWuxshbBWM0XA0RLpFCCbsIAA)

#### Code

```fsharp
let save : string -> Order option -> Order -> Async<unit> =
  (* same code as above *)
  |> withTransactionFromConnStr
```
            

#### Error

```fsharp
Fantomas.Core.FormatConfig+FormatException: Parsing failed with errors: [{ Severity = Error
   SubCategory = "parse"
   Range = Some tmp.fsx (3,2--3,4)
   ErrorNumber = Some 10
   Message = "Unexpected infix operator in binding" }]
   at Fantomas.Core.CodeFormatterImpl.parse@26.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 31
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2023-01-19T13:03:07Z - 813e63ab5c07fe5f5fd89328b9f5a7375ab43efb

```fsharp
    { config with
                MultilineBracketStyle = experimental_stroustrup
                KeepMaxNumberOfBlankLines = 3 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by cmeeren** [comment]
Oh wait, nevermind, I see the error now.
