### ISSUE TITLE
Exception caused by long line over 80 characters including method calling and member indexing 

### ISSUE THREAD

**Issue by clkbug** [fsprojects/fantomas#2761]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAPAFASgHQE8BtABgF1cAvK6m2u%2Bhxp5myAGnCgGdEAXXgJYA7AOZdUYQpwigIcqABJe%2BAA7I0kYb3bS5kBQDcAhgBsArusm75xDvPmQAkkKRDeAZQEVkd%2BxAAs1mCkugC%2BvjJB%2BspqEppuOn76xuaWUn4QAIwR9pAAskboADLCiEWIorwAFokZmQBMxEEh8uG6srlKqpaQFfAA8gBmJUKI7somPlGGphYS6Rn1OQ4Aoi5DI1MZUCaDkM1hOR0OXbEaAEawsCa1JylzaAt%2BAMzLes48AE68AGLCpgA5RAAdxMpVu9l4nwsB1aR2mMR6l2uEIgyVmaSCATeaPcKiM0EQACFEINYJ9EAAFIyfIwAWz4iE%2BqLkUJhfhacja8mOelOSKuNze6NS8yxYAArDioHiCcTSeSyrBgUzoEYeM4DLA1YJYEIWRA2YhYVz4Ul%2BXFkULpvdMdsAGzSyCywkkskUgCqKjUnzVGqEWp1Aj1BrAg1MPBNEG5cl5aItF0FLJFDys2wA7E6XfL3YgAMImdVcPN6rhs6C8cmh8MmSMcw7tBHdS1J4UzUWPcUADiz%2BNdCopeUQdPOTOrEeN9bhjfNiJbKLbtrF2wAnL25W7FSWTCHpTW6-ZOdGzZ054mFzaMcu6rZxc6%2B4gAIKDXhMkt0ulGUNGqNgGORWdm3Pa1zSXTttkybI72zTcKXcYcBDgHd9T3Cdf3-MA40UM8oCtZN21TJ57AaddCWfV9PngulEOuXdxR-KdTRnU8gNw1tLw7NM6leaCH0fT5YDMFwABFEDBaiKO-aFJ0PBseSbM4oC0fCwK4vxMn8J0CnQRxBgAFSqCp3CqcleAAdQEeBqlDJpGOPZiThw%2BJtEXK9wLqKU7203SDIqFZazGEzvgsqyamle1bNk6d5MAxTnJUty1OIx0vMKZxBgEdB%2Bh9IxK0%2BFZ0BUCkuC4YMUO7SL5CPP8T0c1j4tcziiPkTJM1S9AACVEDgT54BC6zpX8Sq5GqjCsOierlMawjxUyHt2q6nr4ABMwRyZIZHFfOlxGlTJ0NqvknLpMwTEEMFRh%2BclP34Jk9Obaa7TqNc70W8l4DyE6ztKS7PmuySnWgKoaQJCiAH1gUs6z9ocw7JoSB7rz8RotMKfjaXwfpPhKMt%2BrCiroZili4qmjiZu2eooO2fJUc%2BdHMex3gVrWz4Nq2nbZoJ2MFJ6Y7ToEc7EB%2Bv7bvu0nHqRpY7zRowMaxgQyw%2BvmBaF3L-rvQHgYrJlwchmpOYAomehJ0DEuauR6h4qntIANQxIlhHgYQRFx0Mu2GiBRoO%2BMnONzpVLNiB6k09qfiEisyvtlwnZdwb3eCOSudio34bFxH7HqTyrcKYTYF4ABxPgCqKxASrKmP8bsmqYe9%2Bq8IR9ykZSqmgVBUoSV4FUKjutRRIyoQBF1IRHxcIdmfZ7YGKipjCbquK69Thv07aqnHzBEQhFDoRw71Tx19yswKT02BnFcXhcrK8cAv1zDufnEC-dN8V6nmlfTqZIRz4MJVRFH0dPl74QA8yrjwyPuGSVUE4G1ngKC8JsmpP2elbT6AhNhFHpOceARgCywFKqIFuAtL4HggdFROhs74JXgdsZ4t4qZFyZAIBkbhTAAGlECIBUCfCovBnBElpFvPG2wwHX3GgmNisCH6UIyM8SmGRIBEkLEIAA1psLg-FBIuCBGWRA71kECyLsVUqpYpLsinvZGesM57sTgWTKRksqZEhpLBRAwl5bQE%2BAw-4r54Aen7nqUS0BCy0kHoQ8BI1IE3yTnEXmX1Ri8IJIovg4x8CTAoTYl4ltZGKxicSWk0AEkeAmFsWRbj6RqHgPsSuY1b4aF9ncR%2BVDg5U1Yew7STM-5DHkUYJRKjQyZGIHHT21dsK1ysRItJ9hniZ1kfgtuA5EBZP5qUd8KgzBn0HvokuhjyoT2ksI6pYj751MkS8JusjxjuIrHkBARS-BCMqZwUgvhNBcB%2BKVCQQjQhAA)

#### Code

```fsharp
x().y[0].zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
            

#### Error

```fsharp
System.Exception: Expected dot in chain at this point
   at Fantomas.Core.CodePrinter.genIndentedLinks@1104(Boolean lastLinkWasSimple, FSharpList`1 links, Context ctx) in /_//src/Fantomas.Core/CodePrinter.fs:line 1131
   at Fantomas.Core.CodePrinter.genIndentedLinks@1104-1.Invoke(Boolean lastLinkWasSimple, FSharpList`1 links, Context ctx)
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 425
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 425
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 425
   at Fantomas.Core.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /_//src/Fantomas.Core/Context.fs:line 458
   at Fantomas.Core.CodePrinter.genFile@3662-4.Invoke(Context ctx)
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 425
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 425
   at Fantomas.Core.CodeFormatterImpl.formatAST(ParsedInput ast, FSharpOption`1 sourceText, FormatConfig config, FSharpOption`1 cursor) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 74
   at Fantomas.Core.CodeFormatterImpl.formatDocument@89-3.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 89
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

The long member variable is not the cause.
This problem also arise with short name variables chaining, such as `x().y[0].z.z.z.z`

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this issue.
I'll take a look at this as this is very recent code.

**Comment by nojaf** [comment]
This fix is available in https://www.nuget.org/packages/fantomas/5.2.1.

**Comment by clkbug** [comment]
Thank you very much!
