### ISSUE TITLE
Fantomas 5.2.4 is trying to format the input multiple times due to the detect of multiple defines

### ISSUE THREAD

**Issue by manxjason** [fsprojects/fantomas#2821]
Tried raising via the online tool but: "Your request URL is too long."

Editor Config:
```
indent_size=4
max_line_length=120
fsharp_multiline_bracket_style=aligned
```

Error generated via the online tool:
```
System.FormatException: Fantomas is trying to format the input multiple times due to the detection of multiple defines.
There is a problem with merging all the code back together.
[] has 13 fragments
[LOGGING_DEBUG, LOGGING_LOCAL] has 13 fragments
[LOGGING_DEBUG] has 15 fragments
[LOGGING_LOCAL] has 15 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Fantomas.Core.MultipleDefineCombinations.mergeMultipleFormatResults(FormatConfig config, FSharpList`1 results) in /_//src/Fantomas.Core/MultipleDefineCombinations.fs:line 211
   at Fantomas.Core.CodeFormatterImpl.formatDocument@95-5.Invoke(FSharpList`1 results) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 99
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 525
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

Sample code:

```
let init () =
    Log.init
        { SentryInitializer = fun options -> Sentry.SentrySdk.Init options
          SentryDsn = "https://something"
          SeqApiKey = "someKey"
          ApplicationName = "someAppName"
          InformationalApplicationVersion = Configuration.Versions.Informational
          IsUsingStagingEnvironment = Configuration.isUsingStagingEnvironment
          SessionId = Configuration.SessionId
          ResilienceCacheDirectory = Configuration.Paths.LogsCacheDirectory }
        (fun event ->
            let device = event.Contexts.Device
            device.Name <- Environment.MachineName
            device.ModelId <- Environment.UserDomainName
            device.Model <- Environment.UserName

            event.SetTag("Environment.MachineName", Environment.MachineName))
        (fun config ->
            config
                .Enrich
                .WithProperty("Environment.MachineName", Environment.MachineName)
                .Enrich.WithProperty("Environment.UserDomainName", Environment.UserDomainName)
                .Enrich.WithProperty("Environment.UserName", Environment.UserName)
                .Enrich.WithProperty("OS.Description", RuntimeInformation.OSDescription))
        (fun config ->
#if LOGGING_DEBUG || LOGGING_LOCAL
            let template =
                "[{Timestamp:HH:mm:ss.fff} {Level:u3} {SourceContext:l}] {Message:lj} | {Properties}{NewLine}{Exception}"
#endif

            config
#if LOGGING_DEBUG
                .WriteTo
                .Debug(outputTemplate = template)
#endif
#if LOGGING_LOCAL
                .WriteTo
                .AnsiConsoleLog(
                    outputTemplate = template
                )
#endif
            )
```

**Comment by manxjason** [comment]
Hello, if I trim down to the following then the formatting succeeds via your online tool.

```
#if LOGGING_DEBUG || LOGGING_LOCAL
    let t = "test"
#endif
    let t = "test"
#if LOGGING_DEBUG
    let t = "test"
#endif
#if LOGGING_LOCAL
    let t = "test"
#endif
```

Fantomas 5.0.6 does not throw the error on the original code snippet. In our attempt to upgrade to 5.2.4, it does.

**Comment by nojaf** [comment]
The link I posted above seems to show the same problem.

**Comment by manxjason** [comment]
https://github.com/fsprojects/fantomas/issues/2822
There we go! Was able to create the issue via the tool as per your link.
