### ISSUE TITLE
Unable to format the follwing snippet

### ISSUE THREAD

**Issue by edgarfgp** [fsprojects/fantomas#2844]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKEOY8MAHATrAOb4CGAtmAO4CWALgBYA6Adlu1gMKksBKiAVwDOiAGo1EVMAF4wAIVj5CVRPiHjJACUQAbXKoB00Hv2FiJVVh2tgAygE8W0AILQ6NWG2lWbvgBQAZgJsAWwAtAB8Pr4xeIQkFAYOTq7untGxmX6sAMQ0AWAAkgDythmZMQD0lWA0pWA8NOSkdIhCYABG9mBIAaQCOnRgOqT2sAJD0Aw8RG0ANNSIPZ4A5ENUPEOMLeUVNkFsfgCUYJFgAKqFANL0BpcaVAYACqoBiuQA6vQM43TOLE0Wh4WIEWEdcroRLs9hxQhCWPB8tCYWAjicAL6QObgKAiOjuFhEISoMAAbRxEFA7EgABI6PZ9CTIDQWHQsRSMLSAG6kHQCZBocnWAAM2OskEKCMQrNsNAAXsgxRwACwciAAXQ56KVlLVUDpDIFUBZbJ1nJpPL5RqFHAAjGbMJAALKkAAeABkWYh3dKiIx2dZbQAmYV6zWYbUcqlYWn0xloSDS%2BDFAKeliIWz0nSKvXc3n8kk29hBh2cgCiCJTaZz4p0AUgYa1ZujjoN8agHVgsB0AZjFvz1r1EAAzKWIBKWCJ8HQAGIs3kAOUkOi9vfYdHw-MbEebubbRsgne7a-NloLgqHYGVY6gtlwpGgiDkiDe%2BEQT1IZHIiFa%2BBPmA3Ld2HDDBI0wFtzTjA8jx7Us8ytQtLwAVhvSA7wfJ8X0Ub1YBUfBjBESUuVgYw0hYf8MEAxBt1A3dqX3JkYIo%2BDzzJS8ADZUPQx9n1fRBzlwfR8NIQiWGI0jgQoiA%2Bh0EQaIgMDsD3KDGK7WC9zPQdrAAdi4%2B8eKwt9OBGIQhE4TwhEAtxFCksAZLk4CmyjZTDVU484P7BCL2sAAOPSMN47CnUQcgOlUWz7Ooxyd2c%2BiVITJiPM0xDrAATn8gy%2BPMnRPAi3kHKwECFLovt4o7NTmM81iiywW1RUvND9MQZwAl-czyGaWyqPksBFN1OLXISiqkoHFK7XtBruMwvjbBCmg4By8ib0inq%2BrACDxwYob3I00bvLtEtJqalrf1m8h5u7XKb266LaNi0rBvKnb6OS-b2FtUcjow5xCGCeAABFdCaehwuuzcosKpzwJc9tmVZSrXrYwNrwal1XUKAIABUGGlWwfmnL54H9G9Q1u4r7tbMq4dNXavKRu0UNRt0Mex6Uy1kjN8boQniY40nIZi6GBthk0Eb2%2Bn3s4pn0ZYAIaFdYohJaRQy1dAg2iESSbx8-nMCK3qSspx7qbFumaswW1dOl-g4HweAeYYWzlV1jB9bWjb9Sp0WRrNy9bT863EFt%2BAFwEULVBTQpWnIYkb1tVbDcg43yAGdwV3TGd3haX9Mdcn3qr99KGptxR4CdVOaHTxBM-wZp8VBhqpk-B9fwAfVoInHYTimk5F%2BH860jgQ1QtGfrIexinwT1LId2yde7oWHr7mmXvF82MCDCbxVHpRRkn6e6FD8P8Ej6PY79helOFg8U8GSuvRruuc7z2mC%2BsINDvFMe96nmhLPLu%2BVdH7ZwbuKJuZA3CqHbjQTuDYyYGx7ptL2-dX6D2LJ9bebpRADjkCyREhJZ7axdhqKGV8l4Hm9qgsaxYUaYNdDOYIbhgS4IRCyIghDLzO0vv1chTJKGr19u-RmdD-qwDoAAcR-KrdWplgQcN8sQsAbtE5IONolKhb0sBBiluKJcVAq7PjoCoaUud9CAzlgCMi-wy4hTCmoLq4NuHrRhtBYaGiJZaKtl-FcRAWAMKcGRWUviWgCDfJjWAkokCsiBFdS8K14HuxcW5dSAi35DwDt438LAgRchwoSYKx9zEsnoMCc%2B1h4kCzuovI2sN1GpLQVoou28K7VndBQDo8BSDGVgJrQkeiq55Q5k4j2sY1FuPqdQrAw56rimkaoJo0o6C8iuIgRAuBImLMlHIMgThHbLXyhDPWpCeE1Ncc9PsiN14ji3hwSAcgRgsAANbViED9cYCIlyWUQGXCuVdpFvlkRZBxQFKnk2qb3M5KSLlr0vMOT%2Bty5CfkCm%2Bf6f9oD4GBtk1o8BzgAk8IDaAIwyBkUGQVI5gsyGnKZLfNOXptkPkeT%2BTM9hsymzSewYcGDbkANpemel0BGV0GZay1C6KKD6HgHA0FCDwWqOXmyhpmBhy0NuSstZaMj52JTPcngzyvRlLtMKRRyjEGezGec1slzYXCNuf0ulhlEA8vvumdquAJgxJYP8jWWtLw3WlYk6%2BySFWTKVTo25cyMXfmiTodm50hB7LiQc1aOJ1RKmZEIGcmsSQrXREAA)

#### Code

```fsharp
Program.statefulWithCmdMsg
|> (fun program ->
            { program with
                CanReuseView = ViewHelper.canReuseView
                SyncAction =
                    (fun fn ->
                        program.SyncAction
                            (
#if IOS
                            // iOS animates by default layout changes, we don't want that
                            fun () -> UIKit.UIView.PerformWithoutAnimation(fn)
#else
                            fn
#endif
                        )) })
```
            

#### Error

```fsharp
System.FormatException: Fantomas is trying to format the input multiple times due to the detection of multiple defines.
There is a problem with merging all the code back together.
[] has 7 fragments
[IOS] has 9 fragments
Please raise an issue at https://fsprojects.github.io/fantomas-tools/#/fantomas/preview.
   at Fantomas.Core.MultipleDefineCombinations.mergeMultipleFormatResults(FormatConfig config, FSharpList`1 results) in /_//src/Fantomas.Core/MultipleDefineCombinations.fs:line 209
   at Fantomas.Core.CodeFormatterImpl.formatDocument@95-5.Invoke(FSharpList`1 results) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 99
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 525
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2023-04-14T07:44:28Z - dfc29ff1c5f8d70b8fd580651a79d5de32febab8

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hi Edgar,

Thank you for reporting this issue.
I'm going to write some documentation on how you can solve this problem.
There is a way to pinpoint where the problem exactly lies.

Also, please try and make your [sample as small as possible](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKEOa9zAHATrAOb4CGAtgHQDKAngHbQCC0ALgJaz0A69O-AzAApeAYnYAzMAEkA8tV6ClOAPQqw7eWFL125Uq0QBnMACNaYJBNIBXADaswd0rVg3H0ABY6ixgDRgAO6IllwA5I6BOo6s3qyKyokQEjZ8QgCUYAC0AHxgAG5iiHZGiAlJyhI89KKI9PCS5RXY6ZB%2B4FClrBz0REaoYADaHRCg2JAAJKy0uMhokOz0rG0jGJP5pHY2c0OrmAAM7fyQ0vV1rNTsAF7IRzgALHtgALqrAL53o0%2BT07MDC0sVuMJhstjthvwAIyfLCQACypAAHgAZRaIZF1IixIE4SEAJn2T1emA%2BqzGsKmMx2kDq8FkElR9EQ1Gmdlu3xBm22AwhODxMMwkAAovV6Yz2cc7BJIET3jDyYLKX95qZYLA7DjFaDuWhedgAMwCtanUr4VgAMUWmwAcohAnY0ZqsKx8NtZST5RzftTVeqnRB1lzwU8IPcjQHqLhSNBEAAhRASWD4RAABVIZHIiEM%2BH9GBdbuwxIwpMwCrWSp9ao1RsDYJ5IbAAFZw1BI9G4wmk%2BjYMF8NBSKVTvlYP2OFxcxB84h3cXPcDvf9fdWOdrg-wAGwtyBtmPxxPJgCquFmfYHiCHI4MnHoE7A1hK08LcrJXqpi6rudrOt2-AA7Fudw7fdEAAYWcIwjBArgjHzNgk1ve9ShnCASwwMsAwrd8-RrTk611BsAA4AKjXdO2TOFEHIUxEBzFtEMfLAixQucKQXFUPxw1d634ABOYj2z3LsoLscc6M2JCnw9F95zfdjsJXINuNxQ4G23EjECYCRsyg8h9FvKdkLAVCvhk5UoCXT9cO-PUsEhaFVMAwTk2oSj2DgESbzEh9DOMsB0KgTC5OXYEuPwqF%2BQc9TNOzFzyDc9VRIbAzJNnaTWNk8yOIUvCf1xQ1IvbJhCFSeAABFij0dhs3010GMwJijJYxU2KgRZlk4xSwtxMNVIRRFpAkAAVTw6moTwk1YAB1dh4GxFtCRS5i0uajKAXa7LrIbSFm16pEBuGuohQfMaJum2bPFvdcFsY59S1fMy1ss0LcuwSFN12-r6AkdhEVkE8DCTIVEQIYwjGvW8COu%2BrbrQ%2B7qTap7Ope2z-w%2BgAlRA4HweAzrmht7ihjAGt8-yflWhGOpymzMEhIj0cxpN4GtGwqJo%2BlpEMch%2BhbSEfKa8sWsgch7A4B0mXNJN9G6GjBrfSnNqhPjVIxrH4DhEX2DFxAJfwKXqq3Lx02jbMAH1Ahm7E%2BeWgXycBeW1z5FTjj6oqyFoWR8FRGDcYultIatu7TPhu2Nod7A8Xs52kVdlwPa91hmdZ-B2c57mtoD2Gg-%2BYWHE1tEdb1mW5dDpTw4i44Y-dz32Bg9Xc61guDH11TDbINgaLNi2Lozkz0oeimS668P8qjxEADUg1jRYGl6H2IcJiBif5jDBYHkKkepjA8R60fzVSNhryn%2BpFiIOeWwJnu-Lh-414pZ7N4gPEdtH0rYFYABxLMgZBiDrzPwiF4vBhr3FaD0LL21LlgPE71ji2ntGieMrBgh1FlrMcq31dBjnoEweoFEk5p34MlG6UlA590rPJdeVMGx4lRhXB0RB6B70YFgy4DCDA2GTINWApwkBLCvIlfg9FL6k0CplChd8N7ULpnQ7M9Arz5G7L0PB1F8DoMWFVa8BCcBCMWo1a2K9VrgMHsjTAeIlbOw1uKZEFBTDwFIGBWAYNehwK1ghcSdUibAKvlnIKiMqH8H1E7HAwpgY0T0OcTYABpRAiBcA8POKcWMZBGC%2BwbDo4hqVSGgPIcFCR-icD6kjsE2Mzh6AAGtxRGCKm4eotoYKIDVhrLW39ky-2gjVAsGSlpZJtmArKlCFYFPLsU9MTlEClRrtAfAlU5GGHgAeXQXByrQGcGQLBbjvK6JJtfeYOdRYILbmUrMLJaBsj8YMg0I9gl132UyJJ0YjkXFZBKYJUyKCzHgDKLZy8AqrxDgMsOWB9Q72CdE2JfVE4qPpCUnQFS0RaNevsQBS99G-MMf0vJFygXP2CS4hBZFEA3LzkyHSuB3D8PoC00G4MWxEOhiQzOZCsK5K1JIgJMDgnfzCZmPhdgjpxSMKkwR7ifIdGeHcBYRhzRgwGEIt4QA).

You will probably need to remove `|> genNode lambdaNode` in

https://github.com/fsprojects/fantomas/blob/7575a6ce06e44e18867fd6e2ef66bd6b9433a904/src/Fantomas.Core/CodePrinter.fs#L2371

But this will make more sense once the docs are there.

**Comment by nojaf** [comment]
See https://github.com/fsprojects/fantomas/blob/a3082cf8094f69c2ee51ba76f80e2ff582fa5b3c/docs/docs/contributors/Multiple%20Times.md
