### ISSUE TITLE
Crash when trying to format indexed property with three arguments.

### ISSUE THREAD

**Issue by gubser** [fsprojects/fantomas#2971]
I tried to create an issue using fantomas-online but GitHub reported 'Your request URL is too long.'.

Here's the link using preview version: [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgIIBOJAhpgMxgAUAlGALxgA6AdhBALaLcBGiEmAD6AOgCS6Phy5ywAdwCW6ABZgA5onR0AHmiXt0AGjCYDR0wC8L6Rk1nynDR0-Lt4YAM7a9t0%2BZghiZgNkFGjABuzK5OXAyQxuBQPujohhpeqGAA2skQoE6QACRYuNmQwYn5XCWR5AA2AK7IaHlxYAAMSR2QEh6IRgDKSlbIPXEALDUQALo1AL4TBTNQpTitUFXLtcX1zZvtcQCMO3KQ%2BOS6ADKGiNeDGmrVHccATJ2r83JLNYXyJTKm0gg3gAHkAGa3diIIZYBrjVZ1RotbJHJxvM61ACiHkh0MRvQaEMgX0WO3%2B53W5TQkH4sFgDReAL2KMOqwgVCxED67B8JHQADFDI0AHKIBQNO7MpzoEgtMk-ClI6nA%2BmMmW7faotocsCTblQIbYcjQRAAIUQENgJEQAAVyBReNISJq5HKFU5vlxfnJKbsgRV1UysciDmi9QBWQ2QY2mi1Wm33WAKITQcg%2BfqRWDp9KwdhurgexCKn3KoqqoMMkMq7XsjoANhjcbNluttoAqthcCR05n2Nnc0p84WIBDGj5SxBfVx-TzK7Tg4WwzrcnqAOzNk2txO2gDCDQzXj3%2Ba8Hug6Bto7A44ak695L%2BKsDi%2Bry9Z4d1HQAHFv422k3wPhBFdQ1b3veRvWncsWRfKAl1DD9V3ReQAE4-x3dtEBPBoRzAicSwfJUnwrOC6TfRC6wjV5uj1WNt0QIgIRdE9uG4chr2LKcwBnFZSI2KsNUotlqJOU46JbBMsKGPglDgXCC3wu9CMgx8-WfATXyE2sRK-E5MQkhimJdGTuDkxk8L1LiiLLEjYM0%2BCKJ0z811eLlDPjUhYCaDwABFEClMyXU4%2BUVLkKCeJgqkyO2ZzkL1Y4DToy5dAkCEABVVEGIZVBtdAAHUlHgZ5DU%2BGzoLs6KHMqIx3yovSnGOaNkquNLMsGbFlJyvLCuK1RrwbMrVOI9T%2BJpLZauElyULkY4mxa1L2AhJRdDBHtyEvEhsV0bBbS8Lxh0UvVvyG8K1NnDTxpq9A6t01yTk3BaACVEDgEh4F6kq9UmU6uAi3iwDnNYYsmuL6xOX9ntem14FFJoBCESEpD4LJDWObiAaBwFqu4JoGnSKUYUFG12LSIR0oEqb4tedC6Jet74HwPGCbuYmSFJ4KY2gVRHVNF0RGUPrSXKyLKoDarYorer7oxWjehS0gKEwMESFuM9Pv6w0ToxqLxauyWWWlmauDecT5auRXKBVtX0DhhGSCR6RuFRhKdbF%2BcyNx-GlEJxA2Y58nKbB0SMQM3pLeV1WlDPJnvd9-2Ns5ujud5i8hAFornjd0b7P10Gpbu42IDedzzd0AA1NlzUMeAMg169tZFzHLuBA2qSNvU3iSsvBR8i9Durjw68zzXvt%2BuZzr43PW-zw3C875qy982B0AAcW0bbdsQfbDvrrXx7Af7dY96qEODhr5DeebenFSU7ktdBU0GCncH85b2BUQ6iA8ID7ZdjprLDVsjnKqV0z4F2mp3R64cpQaHYL3dg-d8wjDgRtJotp0qwH6EgIwG1DrXnAmFP6k9AYt0EjWCB1M4hvEhjAl07A8GRGTOwDQv8QJv0MJ-U8BCCLZwumNNUTlKHgwxLTeWzMlAEmuOQAQ8ByAHlgAdFht9fY8OUnwqeoDBHaWESHeQVA5ZxEgJvIQSheC4IaAAaUQIgbA2DBjoH6OaCgiDR4dEIRo0hAjyG3UgR0KgZsjHmkPOwAA1gSLwXkfKw23tIRmEjfabz2gdbhhpAFnRGvw6ePiqYiP0WHIJjoAK2l8tHaAJAzEijiR2D%2B%2BZ-LQEPBQPMR13G8KbsfYGOMEn3woNAUJ2g4SYARL4qhTgqClyMbHFmMJnGmn6egQZwyuZOlwPAYWQCKogL1jPG6uS9FyCoN3Ix1jbEpTtiBSEwT3DhLuP-E4nQD5H3dp0sBQi55%2BLiFQReRiVH313IgKZPs7isWwE0dAeD8xJO3iklpcR0nEMyZo7ZOTz4y30dfIxJiKnmPBQ0TqZkvBuLiB4puyRZgTEqF4QUB1sgeIWEAA)

**Code**
```
type MyArray3 () = 
    member _.Item
        with get (x: int, y: int, z: int) =
            ()
        and set (x: int, y: int, z: int) v =
            ()
```

**Result**
```
System.ArgumentException: The lists had different lengths.
list1 is 1 element shorter than list2 (Parameter 'list1')
   at Microsoft.FSharp.Core.DetailedExceptions.invalidArgDifferentListLength[?](String arg1, String arg2, Int32 diff) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 26
   at Microsoft.FSharp.Primitives.Basics.List.zipToFreshConsTail[a,b](FSharpList`1 cons, FSharpList`1 xs1, FSharpList`1 xs2) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 906
   at Microsoft.FSharp.Primitives.Basics.List.zip[T1,T2](FSharpList`1 xs1, FSharpList`1 xs2) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 923
   at Microsoft.FSharp.Collections.ListModule.Zip[T1,T2](FSharpList`1 list1, FSharpList`1 list2) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 598
   at Fantomas.Core.ASTTransformer.mkTuplePat(CreationAide creationAide, FSharpList`1 pats, FSharpList`1 commas, Range m) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1625
   at Fantomas.Core.ASTTransformer.mkPat(CreationAide creationAide, SynPat p) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1709
   at Fantomas.Core.ASTTransformer.pats@2683.Invoke(SynPat p)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 243
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 96
   at Fantomas.Core.ASTTransformer.mkPropertyGetSetBinding(CreationAide creationAide, FSharpOption`1 accessibility, SingleTextNode leadingKeyword, SynBinding binding) in /_//src/Fantomas.Core/ASTTransformer.fs:line 2683
   at Fantomas.Core.ASTTransformer.mkMemberDefn(CreationAide creationAide, SynMemberDefn md) in /_//src/Fantomas.Core/ASTTransformer.fs:line 2893
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 243
   at Fantomas.Core.ASTTransformer.mkTypeDefn(CreationAide creationAide, SynTypeDefn _arg13) in /_//src/Fantomas.Core/ASTTransformer.fs:line 2619
   at Fantomas.Core.ASTTransformer.mkModuleDecls(CreationAide creationAide, FSharpList`1 decls, FSharpFunc`2 finalContinuation) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3052
   at Fantomas.Core.ASTTransformer.mkModuleOrNamespace(CreationAide creationAide, SynModuleOrNamespace mn) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3136
   at Fantomas.Core.ASTTransformer.mds@3146.Invoke(SynModuleOrNamespace mn)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\FSharp.Core\local.fs:line 243
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 96
   at Fantomas.Core.ASTTransformer.mkImplFile(CreationAide creationAide, ParsedImplFileInput _arg15, Range m) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3146
   at Fantomas.Core.ASTTransformer.mkOak(FSharpOption`1 sourceText, ParsedInput ast) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3571
   at Fantomas.Core.CodeFormatterImpl.formatAST(ParsedInput ast, FSharpOption`1 sourceText, FormatConfig config, FSharpOption`1 cursor) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 66
   at Fantomas.Core.CodeFormatterImpl.formatDocument@89-3.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 89
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

**Problem description**

Fantomas fails to format indexed property with three variables. But it works with two variabels, see [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAspgIIBOJAhpgExgAUAlGALxgA6AdhBALaLcBGiEmAD6AOgCS6Phy5ywAdwCW6ABZgA5onR0AHmiXt0AGjCYDRxk1nzbDG7fLt4YAM7a9Fk2a%2BMAbswOtlwMkMbgUO7o6IYarqhgANoREKC2kAAkWLgJkIboYSlcmX7kADYArshoycFgAAzhdZASzohGAMpKAF7ITcEALEUQALpFAL79qcNQWTjVUPmF6RmllQu1wQCMU-KQ%2BOS6ADKGiEftGmrL21T1M2Nyk0Vpe3M5aJDt8ADyAGYn7EQHSwZT6MxK5SqCU2tiouzkkAAos4-gCwc0yr9IPcJrsXgi3gtIPxYLAytcCWsoTUZhAAMzw4qtdwkdAAMUM5QAcogFGVThT5OgSFUcY88eDCbkSWTBRAIetobSwANGfKOthyNBEAAhRC-WAkRAABXIFF40hIcq4wtFtgeXCecnxxSlHxl5MZCupSWVAFY1VANVrdfrDWdYAohNByO5Wn5YDGYrB2NaILbEGLHRKVtkiR7rd6NsqAGyByDB7V6g1GgCq2FwJBjcfYCaTShTabAv3K7izECdXBd8rdUALXtWkOLdQA7OXK6Ga4gAMJlWOuZcp1y26DoQ1dntlPv23HPSV56Wkz2SqnT4IADnnmqrYaN%2BD4gitgcPx-kDoHOavBe7pXoWk6KjSdQAJxPiG1bhpuZSdt%2BvaZie4pnrm8yXrKE63kqdRbI0yoVs%2BiBEL8lqbtw3DkF2Gb9mAg7TFh7xjqBeFTgR2w7CRC7wUaHR8EocBIamKFHmhf6ns657YSBuE3lxkE3LB2oUZaQncCJZLIcqDHodmmFAfJ7GKSs%2BEqbYWwMnxZGkLAFTOAAIog-LaZa9EilJcj-kxgEEsBixGGBlm%2BoRqokQcugSL8AAqqjtB0qiGugADqSjwFcgZ3IZAHGYFpl5CFnEQeF2wBlFhyxQl7SIpJyWpRlWWqF2Ja5dJGGyaxRJLKVPowvIWxllVMXsL8Si6N8jbkHuJCIro2BGq4rgduJyr3h1vkyUOclscVBT9Xe1lzqNABKiBwCQ8DNdlyoDFtXB%2BcxYDDrMQUHaFynldZj7nZdhrwFyFQCEIfxSHw8SBlsjEvW9mQfdwFRlDE-KAmyhq0dEQhxdhR3cdZMEkRdV3wPgyOo6cGMkFjnnltAqhmlqloiMoLXYnl-kFa6H19UpZWDXItzltFpAUJg3wkCc263a1gabbDAU80VfMWd9gtcFQvHNKLZCUJL0voMDoMkOD0jcFDyow5zcN7USSMo0oaOINTtM43j-MDcqVBwiRYv61LSjbuTjvO67s10yRDNM7uQis5lVyK9zI68yVnvHfIVC2TrhwAGpTjqhjwLEstdgrNtKynKtp2rAve5FOe6GyTm7mthfOCXCdy-dj2jDtLEmftquvGFGsQFQlWN85sDoAA4toC1LYgK1raX8u92Az2V%2B9RXjunBOZyNzQ8nypx6ugUbtLjuCuRN7AqGtRDOO%2BJuW3UBmdUZ3WD-mHH71ZmdTrNCIPyDQ7Bm7sFbimLoYDZoVCNHFWArQkBGFmmtA8qEk7f0KvtPetcvZ1CoH9YBKMhDsDQX4CM7ANAv0-LfQwD8twYMklg3aPUcLXnwRnIWRMdYUyUGiI45ABDwHIKuWAq1qEn2dsw3820upsJ-hwr6dc6h0mIs0ReQglC8FQWUAA0ogRA2BkHtHQK0HUFBIHdzqD%2BHyT1%2B6vTtso-GAC5B0m1sESAOo1zsAANZolcA5JyQNl7SDJvw52i9lqrSYYGD%2B8iv6KJwb-cyI91bKjpL7ZoOozQCUQM5IO0ASA6M5OE2s98UyuWgGuCgyZ1q2MwRXZOO99oO0poCSxWo-HaGBJgUEKiCHBDpNnLxIcOm6goNAHp6A%2BkDPpuaXA8AOaf3ytg5WQ8a7pNUcMhuXjDHGOisbT8fwfFOACacN%2B2x6gby3i0hGu8-5cIPu4yeXjpFn1fIgcZTtTjUWwBUdAaCUzROXrEhpwQEkOIUQPFJLj-4-XkHSI%2BXitElN0UCso9VtKuBscEOxsMIgjH6HkVwbJVoJAJeMIAAA)

**Extra information**
[ ] The formatted result breaks my code.
[ ] The formatted result gives compiler warnings.
[x] I or my company would be willing to help fix this.
[x] I would like a release if this problem is solved.

**Comment by nojaf** [comment]
Hello, thank you for this report.
I took a look and found a solution to this problem.
The short version is that the AST the parser produces is rather misleading.
We had a workaround for this but never considered any cases where there are more than 2 elements in the tuple.

**Comment by nojaf** [comment]
Fix available in https://www.nuget.org/packages/fantomas/6.2.3
