### ISSUE TITLE
Many Ifdefs seem to cause parse error

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/fantomas#3013]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKBbBBXANosAYgM4AqssOA1gJYAuAdAKIBOzszAEgIYB28O1HgHN6JREVpEAOsyk8ZcgMTUAZoQCCAIQAyjAPoBhAPIBZAAoBJXQCU9ZgJokORgHIKesAA6IehLgCM8ejMATwAPb2haWHdFH3hVWNUNHX1jcytGWwApdQA1dQBlA2sLMxJ3Lx8-QMR6E1hoAAsuWPjE2R5lNQBCAi1dQ1NLG0rvX0YIxCiYzoB6OZ5ERCR4MBV2MAADeFhaJdowWnFaLaPYMAB3dkp3AG0AHjEJIgA%2BAF02vg65PEOuHA4Z6SMAAXncEAgxwk2moEjAUkg6kBYGB0kgYDuEMhOOs4lwtDR9ABQJO0k62IgnwpnUejB4tGYITMsEEtA%2B7j%2BYHQXEEYC4zCEADcwUk1P1UkMMjY7I5nG5OjjQlMZvRmFgeGj%2BYC0V8EioxSlBukRlk9LkCsVSuVKWAGs0uGqNVqSbrOnFvgb3ck%2BgM0sNMtZbUT1ZqyQB1OhNAzaCzqQVETHvMDx5hcEL0RDoTy0ELa0kvPWqSAAGnAUCIiFotEEQiIqEx5YgoBxEEgABJc94G5A2aWm5CO0KAVhkGg7gOcQAGMutwcWPg%2BWiFagAL2Qs7nYAALJOwO8BwBfTfNvcdrtjqB9k%2BD9vDnCjhsTrdgACMN5xkBMXDCsKW2h8IRaCafsX1fAAmKc9wPHFjwHFtW3PEJuzQSB4iMFQ-0QQpczwUDELvEdL2fLdwI-Qd6XgDCsPwudIBwFRIGgo8bwQz9O2Qy9IH8cgcFo2970fcc9wgABmci2wXStmFoAhBABFxEEuAQln4nFGVHZjYNYs8OJQqAeIoNSoEIh9iJEncJKgQpPC4aBEE0RANmYRAzAFLh0CrRBmGMqF1UQLTITgnE2NvC8e0MvjyKHIinwsgBWKzIBsuyHKc9hEG0WBLm86AuErBchUaLga1gHhfKOfzAogYLIVCts9K4yLjJisy4pfAA2JKUvsxznMQABVTxvGYPKCp4Iq8tK8qrJUAFK2qsBatPOjGoi3iWtMoTGxfAB2brbN69KXIMHB8qIAwyokdUZh82b5oCucYKCnTVvC1DmuirbzJfAAOA7Ur6jKTCzfxvIquacAWp6WPg3T3oMjavsEn6twATgBo7%2BsunAyohh7FuWsB6pMhHuKR3SUfardXxnCzksOxB1BUY5mEu9AeQqjTHtbZ6ategiyc%2BynYuEsD33pnq0v6wos2oOBcZmizIeh3nYZC%2BHOPWozkdFnaabIyXGeZ1nZfQeWKDxqzucJgX2KFinVqpsWafEo3UvjWANXgAARRABHN1muaqmHtLht6tdQ68Rbal251fbcku-MILBUEgmh8QomnYWhI3gYCKqg0OXvDwXI6vBlNud-X48S%2Bnk9T9OfEYKHsOzmS84LqyOqLtWw41iP9N7SvddjmvW1fLr65-BcVGoMIjBGkr2EmTwXKIIhqCtizft7nE%2BaWu2wvL4faCrvWSPj-bp7CPE4GYeBO5Aqztz3yED6JkmkKH6OnYvizXz-Rvnfdg8AXBYHQGDZgGELDHHQPWKyr5bal3tifdABJqAqUQAQdgPJqzeRIFrUe21L4TwxvTEBD8TAYKwTg5geCg5JQdGmKI3k9CXGoPnECyCB5lx-iPGOJCLKQSTj%2BVM6YjDMFhBIJ%2BFVd48LqprfhZ9iGoznOBCWL4vxiNYBIqRcJaDgMgd5GBcCEEAIUStPhXF0E4BrLQ3BJVWaEO7Ko6m6jDZaPESESR0jaDULsZgwQ2DHH4LuvTZhdlWbsM4QXSxxMlFcV-gRaupCcTgTdlo5OeQiKaEEAkYQsirLyOLvzFBx9lHnzHmkyE4FE43wIBqKIW8eB5O%2BIU2Jz8LKv3iV-NaUcBF-2qcIuuWSfw%2Bz2AAcSrKvdem8ypFJ3m-Kk6tFGDyao7FJ-8XzgSnloxSylgmOVoDlHwLjEB%2BznjwOgLT1B8BBsY5g5iXw21KYfcpDUHY60EWo1s4Fr5eIEEIHgjSeDNLKiuYFJUsAuTIAuJADISotPxq3XpiTtZRR%2Be4v5QDAWsx4EioUmUypCAeVAy5ggblXRRarfeqyrGoKHsLIZQidnkKyRgrC2gPL%2BHgFwU6sBN7CAOVgmlPM6X9zWdYjFVTWVblEnTLRq9vLUE8oinAABpZYnh4VLgXJoNMYKukvhVuK9%2B9KEnrJlW4uOrZRKaK3JATQZ0eCUCwkQT23tFISBWAE%2BxwTZniHmTwZ5W5Xl9xLrwxlGzvkst%2BTiUSnjHWaAFEDFyPs4TQGYKq%2BSxx4ADWuWVP20AzppmmmKtFVrUK2P9UsA1dlKBVhwiEPCNrx4JsyY6v1QS60sMbcuXCG4IlpmzCsJibzP7ooGSorFtqE31K0VqxAnhk5GKgRhZ1vA3XBNDfHKcyz9wWr6V8zFcbsUJtGY6kVRzjqIG7Vg9mngsC0CRWVQNG9kXWxDhGspUaKkxtPVs4ZL5RJ7Mdcq7NaqX04BbubIgxqtymsJuWd4m5exEGINQBsSHDxAA)

#### Code

```fsharp
module FsToolkit.ErrorHandling.Tests

#if FABLE_COMPILER_PYTHON
open Fable.Pyxpecto
#endif
#if FABLE_COMPILER_JAVASCRIPT
open Fable.Mocha
#endif
#if !FABLE_COMPILER
open Expecto
//needed for `dotnet test` to work
[<Tests>]
#endif
let allTests =
    testList "All Tests" [
        ResultTests.allTests

    ]

[<EntryPoint>]
let main argv =
#if FABLE_COMPILER_PYTHON
    Pyxpecto.runTests allTests
#endif
#if FABLE_COMPILER_JAVASCRIPT
    Mocha.runTests allTests
#endif
#if !FABLE_COMPILER
    Tests.runTestsWithCLIArgs [] Array.empty allTests
#endif
```
            

#### Error

```fsharp
Fantomas.Core.ParseException: ParseException
  [{ Severity = Error
     SubCategory = "parse"
     Range = Some (30,0--30,6)
     ErrorNumber = Some 58
     Message =
      "Unexpected syntax or possible incorrect indentation: this token is offside of context started at position (21:1). Try indenting this further.
To continue using non-conforming indentation, pass the '--strict-indentation-' flag to the compiler, or set the language version to F# 7." };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (30,0--30,6)
     ErrorNumber = Some 10
     Message =
      "Incomplete structured construct at or before this point in binding" }]
   at Fantomas.Core.CodeFormatterImpl.parse@39-6.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 47
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

Further Examples: 
 - https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/tests/FsToolkit.ErrorHandling.Tests/Main.fs
 - https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/tests/FsToolkit.ErrorHandling.AsyncSeq.Tests/Main.fs
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-12-06T16:47:58Z - 0f8ee237a452f3772afe7989e031b5f65ba389f5

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by nojaf** [comment]
Hi Jimmy,

That `main` function leads to 5 define combinations:
![image](https://github.com/fsprojects/fantomas/assets/2621499/6332eb99-aabb-4a8d-bf44-c9a1ed626dfd)

I believe the `FABLE_COMPILER` case, is leading to invalid code and cannot be parsed.

Try
```fsharp
[<EntryPoint>]
let main argv =
#if FABLE_COMPILER_PYTHON
    Pyxpecto.runTests allTests
#endif
#if FABLE_COMPILER_JAVASCRIPT
    Mocha.runTests allTests
#else
    Tests.runTestsWithCLIArgs [] Array.empty allTests
#endif
```
as a workaround.

**Comment by nojaf** [comment]
/repo-assist feels like a Jimmy problem here.
Not all hash directives combinations lead to valid code.
Not much we can do here.

**Comment by nojaf** [comment]
Though luck Jimmy 😛

**Comment by TheAngryByrd** [comment]
Rip fable projects
