### ISSUE TITLE
"Incomplete declaration of a static construct" which the F# compiler accepts 

### ISSUE THREAD

**Issue by Smaug123** [fsprojects/fantomas#3033]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAYrLGALwA6AdhBMGALKIC2YaArhQJbpgC0AfGHZcwAX0qVqYAM7oAhug7QwAUUbYsaQsXJVJ1Wg2YkwACgBm7MAA9eAs7I4AbAO5cAFmDKQAqpzWOmRAp0RHgwCwpoBVgKLwBKUUgAGnAoKUR0BQoAcylUMABtVJpi6kgAEixcfMgOYOTSiAqAN1lHVmQ0Ir1qAAYUnqaASQokYIBlDgAvZAHBgBZGsABdUpE5kp6Kqs6oOvQGrfLW9t3uwYBGDb1IOlkrABk6xAeg7PQ3Q8uAJl6l1ck61KoCOOxqQXgAHkzE8KIhxlgAl9JC02h18ucet9rijlKNobDZksmo4zJB-mtriCbpUcLtIAAjIiOZFlY5os7EsAAZhxZRG6QATuh8HU2gA5RDORzPVmSdCCjoUwFUpbbOk1JmwFl81GnDFc%2BZ8prjbCyaCIABCiDMsEFiAACrJBbJGBlEIK5dQFUqegDqEDJNSUbTqmhGcyvXr0V0uQBWY1QU3mq02u0vWDOD3QWTpEbNWA56IUL0QH2IZUB1WgjXhrU6tXs-WxwZgABsicgyYt1tt9u82FwgpzeYoBaLHBipfCbXSlYggf0jbBdcjuqbMcKXIA7J3u6m%2B4gAMKOXNSI8xGSKqJ26f2Rxzv2U4HL2tQetRjec1sADj3Zp7NN7UMBkPTvWcKyfFUXxrMN3zXRsTk3TE9AATn-FNe3TC9HCnRN70fPR-QXasaRXeDtU-JDv0ufouS7ADEAAQTMEJBQvRhGFkady3nURSJDciI0o9dqINVsLiuej9yw%2B1xiYRRtTwrkCMgojnyDV84OEhsjjElsfgwi0WLY%2BTGEU3CS0TXioKrGCyLfHSqI5cTLl5aTGKYwVYHYeAABFEBlcy2J4xU1MkYj%2BPswTHP2Zzmy3CSjXou4rCGMwABU3CCcY3DtdAAHUOHgD5pz%2BWySOitkhLi0SXIMnoLgTFL7nSrKgmUB94Ty4UipKz5Ezbcr1OgzTYPpWrEPqxLLg7Fq0ooMwOCsSEh3kO1lCsbB7SkKRJysrkf2GiKNKXcaakmvTppQyQLl3eaACVEDgQV4D60rE3mY7qEixdNgc7TLppfSZsav9Hueu14HFVhGFAwVoSGEJGDyRMLj4v6wGDarHMYVhHAUGU4UIQUuMyD0Mo1OqEpu6gLnQ%2Binpe%2BA6HxwnnhJsmQs7aA3Gdc02IAfVcfryQqqKxoBib6mp5CuV%2BTtUq8l1MEhQUnhkd6BsO76IF%2BgSccBmWppp%2BWpNbW57mV2RVfVjgZBhuGPUR5HUa5dHxcx7GmlDek8YJpwObtLmKapk25dbb5sXo63bY19BWYDonEE5%2BRufo3n%2BaiD1heK0qMYNn2auNq7Tcj9yLdSgA1DlLTqeA6myLXpyOguqqL2KS%2BB675eSyv7nwdgon2uvRkb5vPt1lZTv%2BmKjYOWWaKxZr%2B6sPzYHQABxDJNu2xBdv2iedbbyW5-pD9F9crE5otyVpWea10CzIJKdwAKls4YsmNGECPTd1sbIjTsqfQ258EKlwjoMb490LZMRlNkCgg9IjFkmAg%2BQrB7QZVgCMMYchizgS6ifM6UtNTgO7mXKB4NYEEw9BQeQHBmgZhyL-QU786hcH2v-QYqkiGz1AaQkS4cl56G%2BAzSubMOCEgeK6Bk8BZAnlgHtHId9k4EMIidUaxCz4CN0uQyBPRuR0QtrvD0HA3TBDaAAaUQIgbAOCgjoBGJaF0kRtath4Z7QuUBfY6PivovQ3JzaDEgJaU8FAADWhIpBeR8qMSUMhQiJ3ZnCXeO09qXlCr6IBlUQEd20hfIRV8AnRwtpaZ0slEB%2BXttAQUZixQhHgL4faAVoCnhdPg-CEFeFYy0n7CRydnHmnCRkBEmAkSXwagEiuwSkmBzhIM6Awz0CjPGRnF0ahQhi2yRLLR-DwxAxDCDWmEBuR92CdY2xqVHbw2hKE2QESonTguL0Ke%2Bt27eKEgUiBwjJDchXsElRD8gKIFmcnDi2BWB4P2qk-e6SDoALCt072HzHJfL0T86g3Ib7BJMbU8xchHCdXMlINx3Cume1SMsOYtQpD4D2vkHhIggA)

#### Code

```fsharp
type Foo =
    { Mem : unit -> unit }

    static Empty: Foo =
        { Mem = (fun x -> failwith "Unimplemented function") }
```
            

#### Error

```fsharp
Fantomas.Core.ParseException: ParseException
  [{ Severity = Error
     SubCategory = "parse"
     Range = Some (4,4--4,10)
     ErrorNumber = Some 3862
     Message =
      "Incomplete declaration of a static construct. Use 'static let','static do','static member' or 'static val' for declaration." }]
   at Fantomas.Core.CodeFormatterImpl.parse@24.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 29
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

The F# compiler accepts this, at least as of net8:
```
> dotnet fsi

Microsoft (R) F# Interactive version 12.8.0.0 for F# 8.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> type Foo = { Bar : unit -> unit } with static Empty : Foo = { Bar = fun () -> () }
- ;;
type Foo =
  { Bar: (unit -> unit) }
  static member Empty: Foo
```
 Interestingly try.fsharp.org exhibits a similar failure, though.

(There's an obvious workaround, namely to add the keyword `member`.)

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.
- [ ] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2023-12-29T14:09:11Z - a999b77ca5a024fbc3409955faac797e29b39d27

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by dawedawe** [comment]
I think this is related to https://github.com/dotnet/fsharp/pull/16345
So the net8 F# compiler is behind our parser code and still accepts this but won't anymore with the next bugfix release.

**Comment by nojaf** [comment]
Yes, this fails in my `fsi` of my local `dotnet/fsharp` main branch.
This doesn't feel quite right if this code breaks in `8.0.200`.
