### ISSUE TITLE
cannot determine if Expr AppSingleParenArg Fantomas.Core.SyntaxOak+ExprAppSingleParenArgNode is uppercase or lowercase

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#3088]
> [!NOTE]
> I could not use Fantomas tool report this error because Github was complaining about the URL being too long but the code is already minimal (just a few characters)
> I tried to manual respect the issue template

Related to https://github.com/fsprojects/fantomas/issues/3086

#### Code and expected

```fs
let doc =
    x?a("")?b(t)
```

#### Result

Fantomas crash with

```
System.Exception: cannot determine if Expr AppSingleParenArg Fantomas.Core.SyntaxOak+ExprAppSingleParenArgNode is uppercase or lowercase
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at Fantomas.Core.CodePrinter.sepSpaceBeforeParenInFuncInvocation(Expr functionExpr, Expr argExpr, Context ctx) in /_//src/Fantomas.Core/CodePrinter.fs:line 2522
   at Fantomas.Core.CodePrinter.genExpr@1028-197.Invoke(Context ctx)
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /_//src/Fantomas.Core/Context.fs:line 616
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.Context.shortExpressionWithFallback(FSharpFunc`2 shortExpression, FSharpFunc`2 fallbackExpression, Int32 maxWidth, FSharpOption`1 startColumn, Context ctx) in /_//src/Fantomas.Core/Context.fs:line 616
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.Context.col[T](FSharpFunc`2 f', IEnumerable`1 c, FSharpFunc`2 f, Context ctx) in /_//src/Fantomas.Core/Context.fs:line 463
   at Fantomas.Core.CodePrinter.genFile@4000-4.Invoke(Context ctx)
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.Context.op_PlusGreater(FSharpFunc`2 ctx, FSharpFunc`2 f, Context x) in /_//src/Fantomas.Core/Context.fs:line 430
   at Fantomas.Core.CodeFormatterImpl.formatAST(ParsedInput ast, FSharpOption`1 sourceText, FormatConfig config, FSharpOption`1 cursor) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 74
   at Fantomas.Core.CodeFormatterImpl.formatDocument@89-3.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 89
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

#### Problem description

Fantomas is crashing

#### Extra information
* [ ]  The formatted result breaks my code.
* [ ]  The formatted result gives compiler warnings.
* [ ]  I or my company would be willing to help fix this.
* [x]  I would like a release if this problem is solved.

#### Options

Fantomas v6.3.3+ccaee4a0756c8bc6f6717ae603915f6f5c52b09a

**Comment by MangelMaxime** [comment]
A workaround this problem is to split the operation into several intermediate variables.

**Comment by edgarfgp** [comment]
I still seem to get this error `System.Exception
cannot determine if Expr Constant (FromText Fantomas.Core.SyntaxOak+SingleTextNode) is uppercase or lowercase
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)`  in version `7.0.1`

**Comment by edgarfgp** [comment]
> Can you reproduce via online tool?

Strange. I can't reproduce it with online tool. But when using [7.0.1](https://github.com/edgarfgp/Fabulous.AST/pull/146/files) in Fabulous.AST with the following test: 

```fsharp
    [<Fact>]
    let ``AppSingleParenArg expression``() =
        Oak() {
            AnonymousModule() {
                AppSingleParenArgExpr(
                    DynamicExpr(
                        AppSingleParenArgExpr(
                            DynamicExpr(AppSingleParenArgExpr(DynamicExpr("x", "a"), ParenExpr("")), "b"),
                            ParenExpr("t")
                        ),
                        "b"
                    ),
                    ParenExpr("t")
                )
            }
        }
        |> produces
            """
x?a("")?b(t)?b(t)
"""
```

**Comment by nojaf** [comment]
The online tool doesn't produce `x?a("")?b(t)?b(t)` but adds some spaces in there.
Is that to be expected?

**Comment by MangelMaxime** [comment]
Adding spacing on this line change the meaning of the code.

Instead of being a chain of property/method chain, it becomes calls to method.

For example, here is the result of Fable compilation even if this apply to normal F# code too I believe.

```fs
let test : obj = x?a("")?b(t)?b(t)

let test2 : obj = x?a ("")?b (t)?b (t)
```

```js
export const test = ((x().a("")).b(t)).b(t);

export const test2 = x().a("".b, t.b, t);
```

**Comment by nojaf** [comment]
Feel free to open an issue for that.
