### ISSUE TITLE
Support F# 9 Nullable Reference Types syntax

### ISSUE THREAD

**Issue by krymtkts** [fsprojects/fantomas#3142]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKB6dY4AcCWi8YAZgE6wC2YAFgC604DOKmSAbgEYA2sA5owDoKeaOUaxitAXArp4sWgDtEtdIoCuXLgENuiALSlExREcXQDtAJ45EjfXkX7ijattI59ATnQBiRlaKtNoAHvra8PB4tHiwiowAOqQJQTaIYACCAEJgALyZYAA%2BYFlJKda2mRwAcppceZk5xRpaZYptFekASohwpPAAYgRcRPnAYAAaaIy0pI68RWAt9QC%2BHWlgACrqOFyIQ4gjDTNzigsAVGAn84vLbeuV1Xa0hADiiMpz0IwN4wBaYDQABk8DMADwg8HXM63OoAPlhWgRzTqYDWyUUkAANOAoIwVDEzoxUGAANq4iCgCDUqAAEk6JMgjlo2Ip1MgtLY2i46mQaHJNJpAAYcYL2QBJRRIIIAZTwAC9kKKxWAACxsiAAXTZK2VlI1dIZaCZQVZYo5XJ5fLJBogAEY9YLIABZUIg5RAj68WjUM0qu0AJiFBu1NN1bKpTvpaUZH3gAHliO7EDLrHs-TSLdzeSSBSqA47MwBRKWJ5MZp1cYiQEM6x2RzPR2yMjiwWBcCsQLNW3O2sAAZkLEviploQ0U3KeAHcuI4lX3Zrza2H6waOUaoK32526Zac-y%2B6qh12ZThtBYssZYEYAArubQUFSmHcQReIZfU8M0hvspvWyBbh2Q7dvuNoqmAACsx5QKe56IJexDXogQKwFOpjQNo%2BKSmwsAYTEcQvmAb4fhAX7Uj%2BXZ-i2bZAWunLZtaeZigAbNBkCwReV5GAAqjgtikBhWGKDheGxJi0HENy%2BIkWiq7mlRxqATuIGMX2ADsbEcfBXGIAAwjojCMLpcQnOo0C0NehGSVw0liqGn5yVGG4ATRyn0T2B7gQAHJpZ6cYhRjOogFAcM%2BElSe%2Bdl1hGdHOUpwHuaBTGCl4vlwQhSHGTw4l9tZtmCvZpGOY2cWuQle6qeBdoin27F%2BYgGSSKYxkUBQ2iEcRUUrjF8mldu5UMb2VUOrVWkZUYMrBSI7YEeFNmRQV0XfrFMaKWVdEVUN-oFqN9WNS8pCTcIcDZR1pBLl1Dk9U5q2but8mbZ5-qDrtcEZOQ6hSgAIoceDCAdZ0XYt3XLb1t0miyA0eWB-pHrVrohOKxCbNQHwytQ160AA6ng8A%2BoRwaXUV10leDzJuY9MNinaUHw6ESMox8RbzejmM43jvrQcxhPA1doM3c2xrk1DSV9narF04jijEHgITxvx2gWaQRYhDgRiGWJhFeTzNKFbJJO-s5wsbYNT3Uxpks9H08Ds-j0Gqjr1J62R%2Bpg4LUDGw9ptU4Kdo%2BZbvTXvAtQhaYibii8FDEtBdoyS7YAUYa4MUJoMSzsoAzXm19CmJsMYi5V-qpbVVtB86qd4On%2BxZ4rANsdAbikOeB0APpTrj%2BNx8Vhtk6aBdbWKQZsQj71N1Y8akJC2Md5zfba13BuUUbfcm9DyU0gGI3gS6oSj9o4%2BT6CtAh6FpDh5H0diwv-Ok%2B7kAp1wadzpnpDZwdefNv3ZuCgGO3b3vB8p7l0fpXZ%2BNcc6kEIjARuzdTBtxnjWIm%2Bsb49zvp7KMlN17UgDC9beCMABqDEsiOCiGcW2s9vKOy1EtciK00Ery9mvPsAY4Z4NCAMT65kxLEKlPMchhEHbX1oW7f86DGyYOYbTNhIQvoKHeLQFWas7CMDEvw6C88kHx0TuucG8VV6i3AgGCW29pxV0vLQNCHwP6IB%2BjLRQ0QxIZClEFUOpBL7gU6rzYmKCl66Puhg72WCIABgtv-WcvBFAcPMPhRQcoImK3UEYTYsBJTSmCDEqyEUhGuwFv%2BPRjCDH5n9mEg6E4YhsGQnEXgLjT62McA4kymT5rZITnQvJ-jxGBOYcXPBFdkxAgfBweA2h9KwBUWcUxc4mn5V1jQnJt92n9X0YXMU-Yarb0UaYP6HxghcAANKIEQDgVJOzJRZCbuYChKo8oLVmSDYRuTqJLIKSswU-Yt4qkgFkHQigADWyZGDvVgJ9YOzxCDAKfsoRR6sVGNOgp4u5fMHkLKebRF5A83l-0%2BVkdw40bGglEH9RwitCDcXsXEH60AdBNwyXNGZTs5mtJEYyB%2BkL4JN2gL8lQqYrDpi-j7Gk-ZcGfIhaA5Q5zzxctoDyvltVRAPlsPARBXjkHItQaIhhASmHgX7Kwz5ByjkIxPmHYg3ztB-IBYRaqVCwDO27r4u%2B%2BStWFNWVIz5kzxU6VFVXFqOB1DpLEtC5Rmt4XnVuQy%2B58z1Woopl0nVxjPmbLmI%2BII3JmbCFcNM8N1Cwy4k1MqJkjABgqJJDckAKwgA)

#### Code

```fsharp
// copied from https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-fsharp-9/#syntax-additions
type AB = A | B
type AbNull = AB | null

type RecordField = { X: string | null }
type TupleField = string * string | null

type NestedGenerics = { Z : List<List<string | null> | null> | null }

```
            

#### Error

```fsharp
Fantomas.Core.ParseException: ParseException [{ Severity = Error
                  SubCategory = "parse"
                  Range = Some (3,19--3,23)
                  ErrorNumber = Some 10
                  Message = "Unexpected keyword 'null' in union case" }]
   at Fantomas.Core.CodeFormatterImpl.parse@24.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 29
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```
            
#### Problem description

Fantomas doesn't support the new F# 9 Nullable Reference Types syntax, resulting in a parse error.

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved.

#### Options

Fantomas main branch at 2024-10-29T08:28:00Z - b7dca797317471654fc693ed5a056cfb90bd73d4

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>
<sub>PS: It's unlikely that someone else will solve your specific issue, as it's something that you have a personal stake in.</sub>

**Comment by krymtkts** [comment]
Thank you for your information.
