### ISSUE TITLE
Exception when code for no defines is empty

### ISSUE THREAD

**Issue by jindraivanek** [fsprojects/fantomas#480]
Issue created from [fantomas-ui](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=MQSwZgBAyg8gsgUQCoAkCSA5A4gWAFAA2ApgC4RgD2FEAvBACwBM+wRAdgCbhA)

#### Code

```fsharp
#if SOMETHING
let foo = 42
#endif
```
            

#### Error

```fsharp
Exception: Fantomas is trying to format the input multiple times due to the detect of multiple defines.
There is a problem with merging all the code back togheter. Please raise an issue at https://github.com/fsprojects/fantomas/issues. Stack Trace:    at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Fantomas.String.merge(String a, String b) in /build/.deps/fantomas/src/Fantomas/Utils.fs:line 59
   at Fantomas.CodeFormatterImpl.merged@445.Invoke(String a, String b) in /build/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 445
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in E:\A\_work\130\s\src\fsharp\FSharp.Core\list.fs:line 221
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in E:\A\_work\130\s\src\fsharp\FSharp.Core\list.fs:line 233
   at Fantomas.CodeFormatterImpl.format@431-1.Invoke(Tuple`2[] _arg1) in /build/.deps/fantomas/src/Fantomas/CodeFormatterImpl.fs:line 445
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 416
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1153
   at Server.Result.attempt[a](FSharpFunc`2 f) in /build/src/Server/Server.fs:line 23
```
            
#### Options

Fantomas Next - 3.0.0-9/15/2019

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `PreserveEndOfLine` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `KeepNewlineAfter` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
@jindraivanek https://github.com/fsprojects/fantomas/commit/253164d98f556939c1ea338f8984dcd39bb6ac09 fixed the original bug. Do you think your changes are still needed for this?

**Comment by jindraivanek** [comment]
@nojaf Not needed anymore, I reverted it c198b3af318e2e673eda9e772153f4d50a103edc. Thanks!
