### ISSUE TITLE
Bug: Hash directive in computation expression

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#977]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIBtEBcwEsA7fHAEQCMAKASjAF4AdAJwcI3YIDMxDY9KAYvmwA6AKIAPfAGcc0yvHJDsAOQCGAW0TVaOABaI2zVh1NhseRcsT0w1kQGEmiNTkQKlwxOq3VjbM3YrLxFSGQAHWGl3WgAfAD4CAHNeZ39AizBoZ1dEAGUAR0xbHPhCzGswBhgct2r0swBXaSIksEo4QkJEaBx8WEIaWkpORrZOtgBaRIbAiBw1aQBrMGAqlgC5jnhYAEIsgcIRAHlwwwBBaQBPQmgaWa2MC32AfVsJ8QkexrdLm7vsi43OU-BsAMT4bikMQAIQAqgBxB6Pcy4fZ6RYOTD4QxyWwY6RYnGEOT3DYo9iQnh8doEom46S6AxGckU0yZaKIMpFEoubkVLxVSCc%2BD1Vls9jPMBvOgHLqfb6-a63SgikHIiVk1hgwzwSEarYGjgAX2okAANOAoNEcH1CElpKgwABtK0QUCmSAAEhwVzOTsgRBwFrdGG9ADc1JhGsg0K7AgAGS2BSAASUISBJeXwAC9kMmzAAWUMQAC6oeNBfdJagPr9sagQZDnq9kejDfjZgAjFWOJAALJqCQAGSIiGHhiS%2Bmb3YATAma%2BX2JXQx6%2B3X-WhIORYLBMDP2BGozGnZ3TLPe4e8ogNPg4JgBuccGIM8dOKPugeOJwo9FFxXezXQ8Nwbbdd33S9azbE84xrCAAGZIIgSA8nCNRoEQGFEE4WBnAABTUJhNFwRAmC-dgcCYGN-2XQCa29X1NygHc93IqDjw7OCwELJCoFQ9DMOw3Dx1gAB3UjoEWRB03DWBJL6AY2PmKjEBojAV3YICwxAgMWIg%2BjWw408uIAVl4lC0IwrCcOcOFwjOJhJOiGS5NcfpCCUsAf0wP9TCXdS6JbRjQL0tij3bYzAgANnM-irKE5wsUWQkBlkKjelwzzvN8jh-IgDSMC05CdK3ULIPCmCXS4gB2WLLMEmzEH7G9yFIrLf1UvyANXAzgt08CwsMiLYMCAAOOqBOs4SHD3RTeOyzrcu6zTevrfrWPKobKrPDgAE4Jow85ODcJgZo0DQ1E8yjqK62ieqCtbSoGzboM4wIuyTLiLMmhL8hvO9Zo8%2BaOrU-LAvXPqno2gzXsi7sey%2BuLECOk7r1ve85q467FvYPKwAK6sHqYsDoZbWGRrncz00zHBjkIAAVJgrgAdRIPR2p8nGMDxgnVlW4myphoyKdMLtEMR%2BrziYWAxngUhEGxW8TqulTQfx8HgMhxsSUG8mqvenivsHCRU04enmTETm8j0XCcFZ%2BBp14wsF1ugL7ohx7teDF7hf17szKNod004fAJFOUjXFwyRwmcaQWkxwITJdpa7pWonQKbH3hr90WYsDiQACUelw%2BB7cdrjnbV3mitrLXAx1rPtq4rtavzqWiKuY4mFHWQy-Zp3k9x5bCv5jOG6F7OdvYLtxvzgA1DiYSIPV7T7zzK9dsH3c1z36%2B9iem-e-b84EMZencpeM1aNeB6rjXtLrwWyd9qeMHncz%2B0aTA%2BmxboYQfaASwYREUAbgaQdM8jERmtGDQQMuILTvtvB%2Bu8n7rj1q-CAs4EYphUIgUSv9BI4HEoYem9Z5Yh2IApQg5wMzNQ0K1Jgjpgac0QWnD2AtnoHzemYWcF4voAGlECIHCKbc2hh0yQK0B%2BfM8CQab3Vkg4qddM5cLhuecWKZjaW1vNIPQN8K6D25sPQm7CQqcOfpPLis5DYpmzPabAUskiNC0CSZmiByD9gQDIwICD5HV1HutfSFjD48IDimc42IUin1uFQ7MKRXCNGcPTWA1NcRuQTmYXxKc3ZsJ3hw0maCX5WLzuE7%2BpFCBuXDCJe0dCGHkKICQdyTDZEsL8ffJRKDzGFMsYEWcrdbGUTvDgTxSAOY5SHsuK0pYCyBmkAIFoToEHGiAA)

#### Code

```fsharp
    let initDb() =
        if not (File.Exists(dbFileName)) then 
            let dbFile = File.Create(dbFileName)
            dbFile.Dispose() |> ignore
        let createSql = readSqlFile "create"
        using (connection()) (fun conn -> 
            task { 
                do! conn.OpenAsync()
                let! _ = conn.ExecuteAsync(createSql)
#if DEBUG
                let! hasClients = hasClients()
                if not (hasClients) then 
                    let seedSql = readSqlFile "seed"
                    let! _ = conn.ExecuteAsync(seedSql)
                    ()
#endif
                
            })
```
            

#### Error

```fsharp
Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|tmp.fsx (18,13)-(18,14) parse error Unexpected symbol '}' in expression|]
And options: { SourceFiles = [|"tmp.fsx"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@61-2.Invoke(FSharpParseFileResults _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 416
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@436-3.Invoke(AsyncActivation`1 ctxt) in /Users/chethusk/oss/FCS/src/fsharp/service/service.fs:line 436
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
```
            
#### Problem description

The compiler cannot create AST for some reason.

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 07/14/2020 19:31:03 - 3416b5154ceaf908f07c34331d425aebb54ff863

| Name | Value |
| ---- | ----- |
| `IndentSize` | `4` |
| `MaxLineLength` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `MaxElmishWidth` | `40` |
| `SingleArgumentWebMode` | `false` |
| `AlignFunctionSignatureToIndentation` | `false` |
| `AlternativeLongMemberDefinitions` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
The computation doesn't return anything if `DEBUG` is false.
There is still a bug if it does:

```fsharp
    let initDb() =
        if not (File.Exists(dbFileName)) then 
            let dbFile = File.Create(dbFileName)
            dbFile.Dispose() |> ignore
        let createSql = readSqlFile "create"
        using (connection()) (fun conn -> 
            task { 
                do! conn.OpenAsync()
                let! _ = conn.ExecuteAsync(createSql)
#if DEBUG
                let! hasClients = hasClients()
                if not (hasClients) then 
                    let seedSql = readSqlFile "seed"
                    let! _ = conn.ExecuteAsync(seedSql)
                    ()
#else
                ()
#endif
            })
```
